### ISSUE TITLE
Kineticist's Weapon Infusions Volley effect not applied

### ISSUE THREAD

**Issue by ThiefMaster** [foundryvtt/pf2e#14242] opened 2024-03-16 20:04 UTC
When doing a ranged Impulse attack (that's configured to use Volley in the infusion) on a target right next to me, the roll option for the -2 penalty is not shown at all, even though the trait is correctly added.

I tried with longbow for comparison and there it works fine, so the bug seems to be specific to that feat.

**Comment by stwlam** [comment] 2024-03-16 22:00
Duplicate of #14156

**Comment by ThiefMaster** [comment] 2024-03-16 22:01
I don't think it's a duplicate. I thought so as well initially, but the fix from that other issue is already included in the latest release, and when I tested with a longbow it worked fine.

**Comment by stwlam** [comment] 2024-03-16 22:03
You're right, but it's fixed in the next release with #14238. As for the toggle, I'm not able to reproduce that. Are you using the weapon infusion action?

**Comment by ThiefMaster** [comment] 2024-03-16 22:09
Yes, and I have applied the effect:

![image](https://github.com/foundryvtt/pf2e/assets/179599/96aa4332-540b-45a0-b4d5-c3238f4b0dcd)
![image](https://github.com/foundryvtt/pf2e/assets/179599/5cccbfa7-3275-480c-a642-e60aad3b5aec)

**Comment by stwlam** [comment] 2024-03-16 22:33
Ah, I misunderstood which toggle you were talking about. That is also fixed by #14238.

**Closed by stwlam** 2024-03-16 22:33 UTC
Labels: bug
