### ISSUE TITLE
[Remaster] Holy Light missing the Holy trait

### ISSUE THREAD

**Issue by mindbane** [foundryvtt/pf2e#11447] opened 2023-11-16 15:06 UTC
![image](https://github.com/foundryvtt/pf2e/assets/354137/9a39cce9-704d-47e9-ad27-2e07b223209a)
vs the pdf
![image](https://github.com/foundryvtt/pf2e/assets/354137/5f26ecd8-a67c-42b0-8024-60175f536e10)

**Comment by Daeke** [comment] 2023-11-16 15:59
Already reported here: https://github.com/foundryvtt/pf2e/issues/11425

**Comment by stwlam** [comment] 2023-11-16 17:26
Duplicate of #11425

**Closed by stwlam** 2023-11-16 17:26 UTC
Labels: duplicate
