### ISSUE TITLE
Automate blood magic for Sorcerer's bloodlines

### ISSUE THREAD

**Issue by Yutsa** [foundryvtt/pf2e#7370] opened 2023-04-11 08:06 UTC
Is it possible to automate some aspects of blood magic from the sorcerer's bloodline ? For instance the Phoenix Bloodline says that when using a spell from the bloodline, you can add fire damage equal to the level of the spell or if it is a healing spell you can add temporary HP equal to the level of the spell to the target.

Would it be possible to have a checkbox to automate that ? I have a PC with a barbarian that has a similar option to use different bonus from his rage instinct.

**Comment by TikaelSol** [comment] 2023-04-12 23:49
This will require notes on spellcasting, we are getting closer to having that. I am going to close this though as it's included in our larger spell improvement tracking issue.

Duplicate of #4882

**Closed by TikaelSol** 2023-04-12 23:49 UTC
Labels: feature request
