### ISSUE TITLE
Cannot cast heightened spells with fixed-level heightening clause.

### ISSUE THREAD

**Issue by micro314** [foundryvtt/pf2e#12848] opened 2024-01-08 05:30 UTC
Version 5.12.1, no modules enabled.

Symptom: When a spell with a fixed-rank heightening clause (as in "Heightened (3rd): effects") is prepared in the specified slot or higher, and the spell is cast or its icon clicked, no chat card is created.

Observed with: _haste_, _slow_, _fear_, _enlarge_.

Steps to reproduce:
1. Have a wizard PC.
2. Prepare _haste_ in 3rd rank slot.
3. Try to cast. Observe that the spell casts correctly.
4. Prepare _haste_ in 5th rank slot.
5. Try to cast. Observe that the spell casts correctly.
6. Prepare _haste_ in 7th rank slot (which is where its heightened clause is).
7. Try to cast. Observe that no chat card is created.
8. Prepare _haste_ in 8th rank slot.
9. Try to cast. Observe that no chat card is created.

**Comment by stwlam** [comment] 2024-01-08 05:31
Duplicate of #12829

**Closed by stwlam** 2024-01-08 05:31 UTC
Labels: duplicate
