### ISSUE TITLE
Furious Footfalls odd interaction with other land speed modifiers

### ISSUE THREAD

**Issue by Olrar** [foundryvtt/pf2e#15843] opened 2024-08-05 22:58 UTC
Currently, Furious Footfalls (Level 3 Barbarian Class Feature) gives the PC +5 Status to Land Speed.  This is increased to a +10 Status Bonus while Rage is applied.
Due to the Adjust Modifier rule on the feature, it adjusts **all** modifiers to be 10, including negative ones.

PC not raging:
![image](https://github.com/user-attachments/assets/b6deb98f-6911-4b79-82dd-94b135806937)

PC raging:
![image](https://github.com/user-attachments/assets/604e90fb-bc94-4012-98b4-8c61b9e26bd5)

**Comment by pedrogrullada** [comment] 2024-08-05 22:59
Duplicate of #15692

**Closed** 2024-08-05 22:59 UTC
