### ISSUE TITLE
Weapon Expertise Feature Issue

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/pf2e#16682] opened 2024-09-25 19:49 UTC
The weapon expertise feature is only granting expertise in martial weapons to Champions, Investigators and Magus.
![image](https://github.com/user-attachments/assets/a7dee9a3-9be7-4987-a385-6677e5377125)
It's description says it should also grant it to Oracles and Swashbucklers.
![image](https://github.com/user-attachments/assets/7cdef010-9f60-43b1-bb10-e9c70114cfc0)

**Comment by pedrogrullada** [comment] 2024-09-25 19:52
Duplicate of #16569

**Closed by pedrogrullada** 2024-09-25 19:52 UTC

**Comment by Ikaguia** [comment] 2024-09-29 15:38
> Duplicate of #16569

That issue has been marked as fixed, but it only fixed swashbuckler, Oracle is also missing that proficiency (or the text is wrong)

**Comment by ammalagonc** [comment] 2024-09-29 16:00
Text is wrong for Oracle - there was a push to get that fixed and it will show up on the next release.
