### ISSUE TITLE
Advanced Weapon Training Feat Not Improving Advanced Bows

### ISSUE THREAD

**Issue by AdAstraGames** [foundryvtt/pf2e#8278] opened 2023-06-14 22:49 UTC
This is all done on Tim Muncie's character builder server:

I have a fighter who uses a Repeating Hand Crossbow (which is an an Advanced Bow). I took Fighter Weapon Mastery (Bows) at 5th.
I took Advanced Weapon Training at 6th.

And yet, when I look at my proficiencies for Advanced Bows....

It's showing as Expert, not Master (and shows up as Expert on the character action tab)

**(Class abilities and feats)**
![image](https://github.com/foundryvtt/pf2e/assets/5984494/af736393-f093-4cea-8b48-7a566177c200) 

**(Proficiencies on the Proficiencies tab)**
![image](https://github.com/foundryvtt/pf2e/assets/5984494/32a6eead-597d-4731-b4db-e649761f22b4) 

**(Actions on the Actions Tab)**
![image](https://github.com/foundryvtt/pf2e/assets/5984494/6d36fc82-3506-4132-9a6f-40709ed4c224)

**Comment by stwlam** [comment] 2023-06-14 22:56
Duplicate of #7605

**Closed by stwlam** 2023-06-14 22:56 UTC
Labels: duplicate
