### ISSUE TITLE
ABP with allow property runes is no longer working

### ISSUE THREAD

**Issue by galaara98** [foundryvtt/pf2e#12293] opened 2023-12-16 05:03 UTC
when the PF2E Variant Rule
Automatic Bonus Progression set to ABP: Allow Property Rune

Items that can have property runes no longer have an interface for them (was working sometime before 5.10.5, is not working in 5.11.2)
remove of the variant rule brings back the interface, but then again requires manual control of Fundamental Runes

**Comment by CarlosFdez** [comment] 2023-12-16 05:04
Duplicate of https://github.com/foundryvtt/pf2e/issues/12279. Will be ok next hotfix

**Closed by CarlosFdez** 2023-12-16 05:04 UTC
Labels: duplicate
