### ISSUE TITLE
Feature Request/Data Entry?: Add Hardness and HP Stats to Armours and Weapons

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#12623] opened 2023-12-30 21:41 UTC
When fighting Oozes armour and weapons tend to get damaged, and right now none of them have hardness or hp marked down by default. The chart linked below (in part thanks to the examples it gives) is clear and unambiguous enough that most if not all items could have defaults for that set and save GMs some time. I know it'd be time consuming for devs to do but if and when any contributors have time it'd save gms on the whole a lot of time if they were mostly all preset. (Example: Full Plate is armour made of iron or steel so it'd have 9 Hardness and 36 hp according to the chart, a long sword is a sword made of thin iron or steel and so has 5 hardness and 20 hp, etc.)

Link to chart:
https://2e.aonprd.com/Rules.aspx?ID=729

**Comment by stwlam** [comment] 2023-12-30 21:43
Duplicate of #12622

**Closed by stwlam** 2023-12-30 21:43 UTC
