### ISSUE TITLE
Spell Activations: Allow Multiple spells attached

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/pf2e#13458] opened 2024-02-01 17:23 UTC
The new feature that allows you to see wands and scrolls you have could if multiple spells are allowed to be attached, add functionality for staves perhaps, or items with certain spells attached. Unsure what the work on this is, but I'd be curious to hear thoughts on this, work needed to make this work.

**Comment by stwlam** [comment] 2024-02-01 21:21
Duplicate of #4882

**Closed by stwlam** 2024-02-01 21:21 UTC
Labels: duplicate
