### ISSUE TITLE
Cannot add Splash damage of a type different from base weapon damage type through FlatModifier alone

### ISSUE THREAD

**Issue by HydrallUrakan** [foundryvtt/pf2e#10567] opened 2023-10-05 21:01 UTC
I've been trying to add an ability that adds a few points of fire splash damage to a ranged weapon attack, and I've found that using FlatModifier to do so does not work unless the weapon already does some amount of fire splash damage (such as through DamageDice). If you do so, it instead just adds normal damage of that damage type. Adding a FlatModifier to add typeless splash damage works (using the weapon's default damage type).

![image](https://github.com/foundryvtt/pf2e/assets/94702225/413ac922-8e2b-4857-a722-e8acdf29864b)

Using DamageDice to add a fake splash amount, it does appear to work:
![image](https://github.com/foundryvtt/pf2e/assets/94702225/33237d14-824b-4162-ba97-8449e99648bd)

**Comment by simonward** [comment] 2023-10-05 21:12
Unable to reproduce. May be fixed by <https://github.com/foundryvtt/pf2e/pull/10474>

<img width="293" alt="Screen Shot 2023-10-05 at 2 10 40 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/9e203026-e346-4ae8-b55c-e7164d805e27">

**Comment by stwlam** [comment] 2023-10-06 21:35
Fixed by #10474

**Closed by stwlam** 2023-10-06 21:35 UTC
