### ISSUE TITLE
Persistent damage of the same type stacking

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#14253] opened 2024-03-18 22:29 UTC
1d6 persistent bleed from wounding rune seems to be stacking with persistent bleed damage from knife crit spec. Resulting in a weird 1d6+1d6 persistent damage condition. 

I think it shouldn't stack, based on this entry from player core:
_Multiple Persistent Damage Conditions
You can be simultaneously affected by multiple persistent damage conditions so long as they have different damage types. If you would gain more than one persistent damage condition with the same damage type, the higher amount of damage overrides the lower amount._
![Screenshot 2024-03-18 232446](https://github.com/foundryvtt/pf2e/assets/87117602/dd8802a4-5e12-4908-828e-ee7ca3e2c17b)

**Comment by TMunsie** [comment] 2024-03-18 22:38
It’s debatable. In this instance you are gaining the damage as one item. It would override a different application of a lower amount. If you already had 1d6 and now would have 2d6 applied this would replace the previous instance, but the 1d6 plus 1d6 is one instance unto itself as it is one application applying the damage at one point in time off of one strike.

**Comment by CarlosFdez** [comment] 2024-03-18 23:03
The "extra" in wounding rune also complicates matters.

**Comment by stwlam** [comment] 2024-03-18 23:46
Duplicate of #13720

**Closed by stwlam** 2024-03-18 23:46 UTC
