### ISSUE TITLE
Need a method of player to invest a cursed item when it has been misidentified

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1798] opened 2021-10-19 08:17 UTC
In GitLab by @fraserstanton on Oct 19, 2021, 03:17

How do GMs handle cursed items currently? e.g. Boots of Dancing. They look like greater boots of elvenkind, and have the invested trait, but players cannot invest an item that is mystified currently. Ideally you want three states of item, unidentified, misidentified, and correctly identified.

**Comment by stwlam** [comment] 2022-11-18 13:07
Duplicate of #2579 (general issue)

**Closed by stwlam** 2022-11-18 13:07 UTC
Labels: duplicate, feature request
