### ISSUE TITLE
Using `floor`, `ceiling` in `[[/r` expressions not rollable

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#15424] opened 2024-07-12 19:55 UTC
This is the root issue for https://github.com/foundryvtt/pf2e/issues/15310, <https://github.com/foundryvtt/pf2e/issues/15422>

For example, clicking the roll link in Glutton's Jaw damage chat card:
```
foundry-esm.js:64198 Uncaught (in promise) SyntaxError: Expected "[", [%*/], [+\-], end of input, or whitespace but "d" found. (at foundry-esm.js:64198:22)
    at new peg$SyntaxError (foundry-esm.js:64198:22)
    at peg$buildStructuredError (foundry-esm.js:64573:14)
    at Object.peg$parse [as parse] (foundry-esm.js:65549:13)
    at Roll.parse (foundry-esm.js:63775:45)
    at new Roll (foundry-esm.js:63122:37)
    at Roll.create (foundry-esm.js:63598:14)
    at foundry-esm.js:62814:41
    at Array.every (<anonymous>)
    at get isDeterministic (foundry-esm.js:62814:25)
    at RollTerm.isDeterministic (foundry-esm.js:60879:43)
peg$SyntaxError @ foundry-esm.js:64198
peg$buildStructuredError @ foundry-esm.js:64573
peg$parse @ foundry-esm.js:65549
parse @ foundry-esm.js:63775
Roll @ foundry-esm.js:63122
create @ foundry-esm.js:63598
(anonymous) @ foundry-esm.js:62814
get isDeterministic @ foundry-esm.js:62814
isDeterministic @ foundry-esm.js:60879
_evaluate @ foundry-esm.js:62833
evaluate @ foundry-esm.js:60854
_evaluateASTAsync @ foundry-esm.js:63436
_evaluate @ foundry-esm.js:63414
```

**Comment by stwlam** [comment] 2024-07-12 19:57
need some examples

**Comment by LebombJames** [comment] 2024-07-12 20:02
@simonward Looking at #15310, you're using `[[/r floor(@item.level/2)d6[persistent,piercing]]]`, which lacks brackets around the `floor`. You want `[[/r (floor(@item.level/2))d6[persistent,piercing]]]`

**Comment by stwlam** [comment] 2024-07-12 20:05
this is the system parser, but the operator precedences should be the same as foundry's (v11 and v12)

**Comment by simonward** [comment] 2024-07-12 20:09
`[[/r floor(4/2)d6[fire]]]` renders correctly in chat:
<img width="289" alt="Screen Shot 2024-07-12 at 1 07 45 PM" src="https://github.com/user-attachments/assets/78945ec1-df87-43da-8275-8e8949b13d08">

But throws the error when clicked:
```
foundry-esm.js:64198 Uncaught (in promise) SyntaxError: Expected "[", [%*/], [+\-], end of input, or whitespace but "d" found. (at foundry-esm.js:64198:22)
    at new peg$SyntaxError (foundry-esm.js:64198:22)
    at peg$buildStructuredError (foundry-esm.js:64573:14)
    at Object.peg$parse [as parse] (foundry-esm.js:65549:13)
    at Roll.parse (foundry-esm.js:63775:45)
    at new Roll (foundry-esm.js:63122:37)
    at Roll.create (foundry-esm.js:63598:14)
    at foundry-esm.js:62814:41
    at Array.every (<anonymous>)
    at get isDeterministic (foundry-esm.js:62814:25)
    at RollTerm.isDeterministic (foundry-esm.js:60879:43)
peg$SyntaxError @ foundry-esm.js:64198
peg$buildStructuredError @ foundry-esm.js:64573
peg$parse @ foundry-esm.js:65549
parse @ foundry-esm.js:63775
Roll @ foundry-esm.js:63122
create @ foundry-esm.js:63598
(anonymous) @ foundry-esm.js:62814
get isDeterministic @ foundry-esm.js:62814
isDeterministic @ foundry-esm.js:60879
_evaluate @ foundry-esm.js:62833
evaluate @ foundry-esm.js:60854
_evaluateASTAsync @ foundry-esm.js:63436
_evaluate @ foundry-esm.js:63414
```

Confirmed that enclosing it in parentheses works `[[/r (floor(4/2))d6[fire]]]`, but that will probably impact a fair amount of rolls in the system.

**Comment by stwlam** [comment] 2024-07-12 20:17
if the problem is that it's rendering as apparently valid, we can make it show red or something

**Comment by simonward** [comment] 2024-07-12 20:19
The problem is that it used to work, but now doesn't. If omitting the parentheses is no longer valid, we might need to migrate.

**Comment by stwlam** [comment] 2024-07-12 20:20
If you can find a prior system version where that did work, we might be able to accommodate it. But the syntax is invalid and always has been.

**Comment by simonward** [comment] 2024-07-12 20:31
Tested on a prior system version without parentheses.
<img width="297" alt="Screenshot 2024-07-12 at 1 30 27 PM" src="https://github.com/user-attachments/assets/6ee956c3-092b-44ec-b2c9-62d846cece4a">
<img width="295" alt="Screenshot 2024-07-12 at 1 30 13 PM" src="https://github.com/user-attachments/assets/2067df38-f5c9-43ed-8b7e-e7f319c905ac">

**Comment by stwlam** [comment] 2024-07-15 02:27
Closing as upstream issue (not sure whether it was an intentional change or not)

**Closed** 2024-07-15 09:04 UTC
Labels: bug, wontfix
