### ISSUE TITLE
Alchemist Archetype feat Advanced Concoction does not promp to select a feat

### ISSUE THREAD

**Issue by Incantatio** [foundryvtt/pf2e#3759] opened 2022-09-03 23:24 UTC
When adding the Advanced Concoction feat to a character with the Alchemist Archetype there is no prompt to select an Alchemist feat of the appropriate level.
This was happening for me on Foundry 9 build 269 with Pathfinder 2nd Edition 3.13.5.16
Confirmed on the Discord that this should be logged as a bug as either the filter for feats like this has not been created and/or the required rule elements are not linked to the feat as expected.

**Comment by TikaelSol** [comment] 2022-09-05 16:11
closing as a duplicate of #1956

**Closed by TikaelSol** 2022-09-05 16:11 UTC
