### ISSUE TITLE
[Feature Request] Allow non-stowing containers to ignore bulk and retain showing items in the Activation Tab

### ISSUE THREAD

**Issue by Monumentalist** [foundryvtt/pf2e#14286] opened 2024-03-24 18:35 UTC
Items like Sleeves of Storage and Accolade Robes all reduce the bulk of their contents, but allow items to be drawn for a single action. Non-Stowing Containers currently flag weapons drawn from that as a 1-action activity and show their contents in the Activation Tab, but do not benefit from setting Ignore Bulk.

If non-stowing containers were able to benefit from Ignore Bulk in the way Stowing Containers can, the above items would be able to be built properly. Retaining visibility on the Activation Tab would be preferred, as their action cost is the same as having a consumable loose on a character sheet.

**Comment by Monumentalist** [comment] 2024-03-24 18:38
Ideally, being able to customize Action Cost and item activation visibility per container would allow items such as Retrieval Belt (free action, bulk reduction) to be built efficiently, but as a layman seems significantly more involved.

**Comment by stwlam** [comment] 2024-03-24 18:44
Duplicate of #14073 and #13609

**Closed by stwlam** 2024-03-24 18:44 UTC
