### ISSUE TITLE
Party Stash - Players unable to update item quantities or gold without Owner permissions

### ISSUE THREAD

**Issue by git-kor-av** [foundryvtt/pf2e#12645] opened 2023-12-31 14:21 UTC
In a recent update (5.11.x) it seems that the permissions needed to interact with the Party Stash seemed to have changed.  On previous versions (5.10.x for sure), players with Observer Permissions could add/remove gold in the Party Stash as well as update the quantities of items.

If you change the permissions of the Party Sheet from Observer to Owner, players can "manage" the Party Stash (add/remove gold, change item quantities).  However this also means they get access to the "Generate Prompt" and "Rest for the Night" buttons on the Exploration tab of the Party Sheet.  Players pressing the "Rest for the Night" button will generate several errors.

**Comment by stwlam** [comment] 2023-12-31 20:32
Duplicate of #12484

**Closed by stwlam** 2023-12-31 20:32 UTC
Labels: duplicate
