### ISSUE TITLE
Weapon Implement not granting critical specialization effect

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#13532] opened 2024-02-04 10:20 UTC
Initiate Benefit of weapon implement feature should grant critical specialization effect for the weapon at level 5.
![Screenshot 2024-02-04 111911](https://github.com/foundryvtt/pf2e/assets/87117602/352f1c4a-0416-45c7-87d6-6699335d3fc4)
![Screenshot 2024-02-04 111919](https://github.com/foundryvtt/pf2e/assets/87117602/8bf3e9eb-6706-477e-a2e6-13ac61a395e5)
![Screenshot 2024-02-04 111938](https://github.com/foundryvtt/pf2e/assets/87117602/33456ce1-8a5f-46c3-aa07-3025567fb9a9)
![Screenshot 2024-02-04 111954](https://github.com/foundryvtt/pf2e/assets/87117602/e8e98929-2e76-4205-8dec-24d06ce4193a)

**Comment by stwlam** [comment] 2024-02-07 00:04
Duplicate of #13584

**Closed by stwlam** 2024-02-07 00:04 UTC
Labels: duplicate, feature request
