### ISSUE TITLE
Actors from premaster bestiary 1-3 are missing

### ISSUE THREAD

**Issue by roguedevjake** [foundryvtt/pf2e#16990] opened 2024-10-25 10:21 UTC
Actors from the premaster seem to be missing in 6.5 (both in foundry and in the pack codebase), first noticed with the winter wolf, but there are a lot that are gone including things like hobgoblin soldiers etc (which matters for official AP linking) 

I checked the legacy pack to see if they had moved over there but they haven't. 

Still there in 2.4.1

**Comment by failwiz** [comment] 2024-10-25 17:18
I assume it was intended:  #16774

**Comment by CarlosFdez** [comment] 2024-10-25 23:15
They should be automatically linked and redirecteed for official APs, if that's not going that's a different issue altogether, but the removal is intentional.

I will let @TikaelSol, @simonward, or @SpartanCPA  decide what to do with this PR, since it seems to be a data entry concern.

**Comment by roguedevjake** [comment] 2024-10-26 02:16
> They should be automatically linked and redirecteed for official APs, if that's not going that's a different issue altogether, but the removal is intentional.
> 
> I will let @TikaelSol, @simonward, or @SpartanCPA decide what to do with this PR, since it seems to be a data entry concern.

It is not, at least not for gatewalkers

**Comment by stwlam** [comment] 2024-10-28 03:16
Closing as module issue

**Closed by stwlam** 2024-10-28 03:16 UTC
Labels: module
