### ISSUE TITLE
Dropped armour counts towards bulk and encumbrance

### ISSUE THREAD

**Issue by Everspace** [foundryvtt/pf2e#16059] opened 2024-08-15 18:53 UTC
I am using Armour in Earth Impulse, and I have made a custom armour and feats to give me the correct training and benefits.

However, in order to toggle it's existence/summoned state on me, and handle it's bulk correctly, I read that you could set it to dropped, but when I do so, my bulk goes up, and it counts against my encumbered status at the bottom of my item sheet.

![image](https://github.com/user-attachments/assets/8544f432-9164-4cea-8437-2f4a4a7636e5)
![image](https://github.com/user-attachments/assets/765bac26-71d9-4f4f-990e-34973bbcea17)

There's also a problem with items that are ambulatory in-of-themselves like Walking Cauldron where they aren't "held" so shouldn't have bulk, but I can't set it to "dropped" but still invested, so I'm unsure of how these should be handled.

**Comment by stwlam** [comment] 2024-08-15 19:16
Duplicate of #9291

**Closed by stwlam** 2024-08-15 19:16 UTC
Labels: duplicate, feature request
