### ISSUE TITLE
Mighty Bul Gae has incorrect stats

### ISSUE THREAD

**Issue by Kalnix** [foundryvtt/pf2e#14440] opened 2024-04-15 04:02 UTC
Compare the stats in the compendium
![image](https://github.com/foundryvtt/pf2e/assets/111199070/2b9a1d4d-1d78-42db-8d16-f275d9175a44)

To those from the PDF

![image](https://github.com/foundryvtt/pf2e/assets/111199070/f0401228-6b81-43f0-bcbf-5a400738120d)
![image](https://github.com/foundryvtt/pf2e/assets/111199070/128b06ef-da35-4dbb-aed9-aa2854b5ef33)

As you can see, things such as HP, AC, Saves etc. are much lower and seem to match the standard Bul Gae from Fists of the Ruby Phoenix https://2e.aonprd.com/Monsters.aspx?ID=1411 not the higher level variant from Stolen Fate.

**Comment by simonward** [comment] 2024-04-15 04:08
Duplicate of https://github.com/foundryvtt/pf2e/issues/14429

**Closed** 2024-04-15 04:09 UTC
Labels: duplicate, wontfix
