### ISSUE TITLE
Take Cover action should apply a condition, not a cover effect

### ISSUE THREAD

**Issue by caewok** [foundryvtt/pf2e#14731] opened 2024-05-17 02:22 UTC
Consider having the "Take Cover" action apply a condition, not a cover effect. 

Right now, using the "Take Cover" action asks the user what cover to apply. But that doesn't really make sense, because [taking cover](https://2e.aonprd.com/Actions.aspx?ID=2307) makes standard cover into greater cover. So asking the user what cover effect to apply and then applying it is wrong for two reasons:
1. Take Cover should only result in Greater Cover under the rules.
2. Cover is situational and dependent on who is attacking. Only if you have standard cover against a particular attacker would you get greater cover. So the decision of which cover to apply should come later, in the attack sequence.

If instead using the "Take Cover" action applied a "take cover" status/condition to the actor then other workflows or modules could account for this status and apply greater cover accordingly.

**Comment by TMunsie** [comment] 2024-05-17 16:09
You can gain cover from things other than taking cover. By reapplying they can gain a higher level of cover, which reapplying the effect gives them the ability to do. Furthermore, the reapplication allows for a quick removal in the event that cover decreases. You can gain greater cover in ways other than taking cover while in cover. Honestly I think the present solution handles this elegantly.
You can be behind a lesser form of cover, take cover as an action to gain greater cover, do something, have that provoke a reaction from an enemy or hazard where you benefit from that greater cover, and then do something that removes the greater cover but allows the lower level of initial cover to still apply. I'd be reticent to remove that capability without a really, really good reason. The take cover macro could be redone to only grant greater cover, but that relies on using the specific macro and already having the cover effect, and as for the second point, making a single togglable cover with multiple levels really allows a player to quickly turn it on or off. The only "improvement" I could see is turning it into a badged effect. Given that this is the first request since this effect was created more than a year ago we can do it but it is very low priority. I'll leave it to @nikolaj-a to consider if they want to do anything here, but it definitely isn't a priority because without special handling it turns into a regression.

@nikolaj-a: feel free to either accept or close.

**Comment by caewok** [comment] 2024-06-03 16:02
All I really want here is a way to programatically know if the user has designated their token as "taking cover." Sounds like that would be "turning it into a badged effect" but that is obviously your call. 

The reason I want to know this is because my [Alternative Token Cover module](https://github.com/caewok/fvtt-token-cover) can automatically apply the different cover effects. It could apply the correct effect when the token is taking cover (i.e., greater instead of standard), but to do that it would have to know if that token is in fact taking cover.

**Comment by TikaelSol** [comment] 2024-08-06 03:49
Closing in favor of the consolidated issue #15855

**Closed by TikaelSol** 2024-08-06 03:49 UTC
Labels: wontfix
