### ISSUE TITLE
Have a way to mark spells that are at will and not to decrease spell slots.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#13341] opened 2024-01-28 16:15 UTC
there are some monsters that have at will spells especially in aps. that when cast will decrease their spell slots. it would be nice if we had something to select in the spell menu thats at will so it never decreases the spell slots. saving having to refresh it each time you want to cast the spell.

**Comment by stwlam** [comment] 2024-01-30 10:19
Duplicate of #1644

**Closed by stwlam** 2024-01-30 10:19 UTC
Labels: duplicate
