### ISSUE TITLE
IWR concussive trait - missing IWR interaction

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5843] opened 2023-01-21 21:29 UTC
Concussive trait doesnt reduce the correct amount of damage when trusting iwr. 
https://2e.aonprd.com/Traits.aspx?ID=401

![image](https://user-images.githubusercontent.com/62528192/213887806-3e8b662d-98ad-4b13-97eb-72fd19ff8739.png)

![image](https://user-images.githubusercontent.com/62528192/213887818-3eb33e2c-eadd-4a81-8deb-8a6bfc1c3923.png)

**Comment by simonward** [comment] 2023-01-21 22:06
Duplicate of https://github.com/foundryvtt/pf2e/issues/5756

**Closed** 2023-01-21 22:14 UTC
Labels: duplicate
