### ISSUE TITLE
Feature Request: Add a RollOption toggle for Inventor's Unstable Actions

### ISSUE THREAD

**Issue by blackquaza** [foundryvtt/pf2e#6808] opened 2023-03-08 06:29 UTC
Inventors get a variety of Unstable actions, which require a flat check to use them again (or a 10-minute break to reset). We should add a toggleable RollOption to the Inventor class (and dedication) tracking whether the unstable action has been used. Bonus points if Unstable actions check this value and change it when rolling the flat check.

**Comment by TikaelSol** [comment] 2024-08-06 03:35
Closing as a duplicate of #9637

**Closed by TikaelSol** 2024-08-06 03:35 UTC
Labels: feature request
