### ISSUE TITLE
Bug: Create Consumable - Quick Alchemy option creating incorrect amount of consumables

### ISSUE THREAD

**Issue by SoundSherpa** [foundryvtt/pf2e#16923] opened 2024-10-17 22:10 UTC
Foundry v12 Build 331
PF2 6.4.1

For an alchemist, their known formulas under the crafint tab has an option to "add this formula to one or more crafting entries". When this is clicked, 2 items are added instead of 1 as in the quick alchemy rules. 

Under the entry for Quick Alchemy:
Create Consumable - You expend one of your versatile vials to create a **single** alchemical consumable item of your level or lower that’s in your formula book. 

No way to lower this to 1 as 2 seems the minimum.
![image](https://github.com/user-attachments/assets/13d54c9a-722a-4a05-afe3-1f8e6b4ecc50)

**Comment by stwlam** [comment] 2024-10-17 22:11
Duplicate of #15647

**Closed by stwlam** 2024-10-17 22:11 UTC
Labels: duplicate
