### ISSUE TITLE
Fr: a way for gms to mark a cursed item but appear as a normal item for players.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#14293] opened 2024-03-25 13:28 UTC
it would be nice to have a box to check "is this item cursed?" the gm checks it and it just appears as a normal item with whatever to hit bonuses i.e (+1, +2) etc but doesnt reveal the true nature of the cursed item. 

currently you have to remake the cursed item to appear as normal.

**Comment by LebombJames** [comment] 2024-03-25 14:13
Is this not what mystification does?

**Comment by GuitarGuyNick** [comment] 2024-03-25 14:16
> Is this not what mystification does?

no mystification shows it unidentified so it gives the game away in terms of knowing its something they havnt identified yet. if you give an unidentified item to someone the meta knowledge of knowing that makes the player aware that its probably cursed. and there are occasions where you want a weapon to seem normal and reveal it later.

**Comment by Daeke** [comment] 2024-03-27 23:59
Mystification, in general, does not give any indication to the player that an item is unidentified. They cannot see the item's traits, and there's no button or label to identify it on the player's end. But they can still 'use' the item as-is.

As GM, you do have to go in and rewrite the "unidentified' item name, description, and icon, but it's very simple to fool a player into thinking they are fully aware of what the item is. Here's an example of the [Bellicose Dagger](https://2e.aonprd.com/Equipment.aspx?ID=2374), where I've changed the Mystification settings to have it appear as a standard dagger:

Player's view:
![image](https://github.com/foundryvtt/pf2e/assets/8185349/93548122-a5e1-40d7-883a-8ffac3ad95b5)
![image](https://github.com/foundryvtt/pf2e/assets/8185349/f1d0800e-0194-4ba2-a3fc-1ea8333b5110)
![image](https://github.com/foundryvtt/pf2e/assets/8185349/a7363030-5542-413f-9b33-dae693ad0f4a)


Now, it _does_ reveal itself as cursed when you actually use it to attack, in this example, but Cursed items reveal themselves when triggered anyway since they then attach to you:
![image](https://github.com/foundryvtt/pf2e/assets/8185349/700908d5-8aa8-46dd-8185-5ea88d0ab860)

I still think this is a good feature request since "cursed"as a trait is an actual system rule/feature so we should do something with that, but I've used Mystification to handle these situations in the past and it works quite well.

**Comment by stwlam** [comment] 2024-03-29 19:26
Duplicate of #2579

**Closed by stwlam** 2024-03-29 19:26 UTC
Labels: duplicate, feature request
