### ISSUE TITLE
Feature Request: extending conditional flat footed to hidden condition per actor

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4744] opened 2022-11-08 13:35 UTC
i love the way flanking is implemented to give flat footed id like to see if it would be possible to extend the flat footed condition to the hidden condition.

the rules state for hidden.

"A creature that’s hidden is only barely perceptible. You know what space a hidden creature occupies, but little else. Perhaps the creature just moved behind cover and successfully used the Hide action. Your target might be in a deep fogbank or behind a waterfall, where you can see some movement but can’t determine an exact location. Maybe you’ve been blinded or the creature is under the effects of [invisibility](https://2e.aonprd.com/Spells.aspx?ID=164), but you used the Seek basic action to determine its general location based on hearing alone. Regardless of the specifics, you’re flat-footed to a hidden creature.

When targeting a hidden creature, before you roll to determine your effect, you must attempt a DC 11 flat check. If you fail, you don’t affect the creature, though the actions you used are still expended—as well as any spell slots, costs, and other resources. You remain flat-footed to the creature, whether you successfully target it or not"

what i suggest is that whenever you drop the hidden condition on a token. if that token is targeting another token you intend to be hidden from it hides you from that token and applies the flat footed condition. without the targeting it would add a global hidden condition.

**Comment by stwlam** [comment] 2022-11-09 02:57
Duplicate of #2602

**Closed by stwlam** 2022-11-09 02:57 UTC
Labels: duplicate
