### ISSUE TITLE
[Feature Request]: Temporary Advanced Alchemy REs

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#16701] opened 2024-09-28 04:58 UTC
I wanted to share a few RuleElements that I feel would be the "90% of the way there standard" and would hold everyone over until the crafting overhaul update drops. I use these in my home game and can confirm they work as of the latest version as of my writing this (6.4.1) If the release of that is close on the horizon (less than a month away), feel free to just close this issue and we can wait a bit longer. But even if this isn't incorporated into any updates before the crafting overhaul, this would be a nice thing to leave up as quick reference for others who are playing Alchemist and want Advanced Alchemy to be tracked appropriately. This requires no new code or scripts, and is done purely through existing functionality with Rule Elements:

### Advanced Alchemy
**Crafting Entry** Replace the crafting entry RE with:
```
{
  "batchSizes": {
    "default": 1
  },
  "craftableItems": [
    "item:trait:alchemical"
  ],
  "isAlchemical": true,
  "isDailyPrep": true,
  "key": "CraftingEntry",
  "label": "PF2E.TraitAlchemist",
  "predicate": [
    "class:alchemist"
  ],
  "selector": "alchemist"
}
```
**ActiveEffect-Like** Replace one ActiveEffect-Like RE (delete the other) with:
```
{
  "key": "ActiveEffectLike",
  "mode": "upgrade",
  "path": "system.resources.crafting.infusedReagents.max",
  "predicate": [
    "class:alchemist"
  ],
  "value": "4 + @actor.abilities.int.mod"
}
```
(I left the predicate in, but it may not even be needed if this class feature isn't used by any archetypes, if you handle the advanced alchemy through the dedication feats or feats that grant advanced alchemy benefits)
Advanced Alchemy Item: [fvtt-Item-advanced-alchemy.json](https://github.com/user-attachments/files/17172187/fvtt-Item-advanced-alchemy.json)
### Efficient Alchemy (Alchemist)
**ActiveEffect-Like**:
```
{
  "key": "ActiveEffectLike",
  "mode": "upgrade",
  "path": "system.resources.crafting.infusedReagents.max",
  "value": "6 + @actor.abilities.int.mod"
}
```
Efficient Alchemy (Alchemist) Item: [fvtt-Item-efficient-alchemy-(alchemist).json](https://github.com/user-attachments/files/17172241/fvtt-Item-efficient-alchemy-.alchemist.json)
### Advanced Efficient Alchemy
**ActiveEffect-Likes** (there's two of them, can probably use a tenary instead, but this for sure works)
```
{
  "key": "ActiveEffectLike",
  "mode": "upgrade",
  "path": "system.resources.crafting.infusedReagents.max",
  "value": "8 + @actor.abilities.int.mod",
  "predicate": [
    {
      "lt": [
        "self.level",
        16
      ]
    }
  ]
}
```
```
{
  "key": "ActiveEffectLike",
  "mode": "upgrade",
  "path": "system.resources.crafting.infusedReagents.max",
  "value": "10 + @actor.abilities.int.mod",
  "predicate": [
    {
      "gte": [
        "self.level",
        16
      ]
    }
  ]
}
```
Advanced Efficient Alchemy Item: [fvtt-Item-advanced-efficient-alchemy.json](https://github.com/user-attachments/files/17172282/fvtt-Item-advanced-efficient-alchemy.json)

(Both Efficient Alchemy and Advanced Efficient Alchemy do not have the predicate, as technically by the existing written rules, the alchemist archetype can pick up both feats through the Advanced Concoction feat) and until an errata says otherwise, I imagine this is the functionality.
### Herbalist Dedication
**Crafting Entry**
```
{
  "batchSizes": {
    "default": 1
  },
  "craftableItems": [
    {
      "or": [
        "item:tag:herbal",
        {
          "and": [
            "item:trait:alchemical",
            "item:trait:healing"
          ]
        }
      ]
    }
  ],
  "isAlchemical": true,
  "isDailyPrep": true,
  "key": "CraftingEntry",
  "label": "PF2E.SpecificRule.DedicationCraftingEntry.Herbalist",
  "maxItemLevel": "@actor.level",
  "selector": "herbalist"
}
```
**ActiveEffect-Like** (Replace the second one, keep the first one natural)
```
{
  "key": "ActiveEffectLike",
  "mode": "upgrade",
  "path": "system.resources.crafting.infusedReagents.max",
  "value": "(4 + (@actor.flags.pf2e.advancedHerbalismCount))"
}
```
Herbalist Dedication Item: [fvtt-Item-herbalist-dedication.json](https://github.com/user-attachments/files/17172768/fvtt-Item-herbalist-dedication.json)

(You may have noticed the `(@actor.flags.pf2e.advancedHerbalismCount)`. A method I ripped from the "Resiliency Feats" from martial archetypes. I found this to be the only method out of my experiments that actually worked, so we're rolling with it. Is it held up with duct tape and bubblegum? Yeah, but it works.)

### Advanced Herbalism
**ActiveEffect-Like (New)** Add the following ActiveEffect-Like:
```
{
  "key": "ActiveEffectLike",
  "mode": "add",
  "path": "flags.pf2e.advancedHerbalismCount",
  "value": 2
}
```
Advanced Herbalism Item: [fvtt-Item-advanced-herbalism.json](https://github.com/user-attachments/files/17172814/fvtt-Item-advanced-herbalism.json)

Some notes: 
- It is set to two so that the math maths right, and this leads to a simpler formula. Also set the "Can be taken multiple times" to 2, as it can be taken twice if you're level 10 or higher.
- A current limitation is consistent with the older version, which is not being able to toggle between whether or not you are in a wilderness to have 2 less "reagents". It also seems like this particular effect doesn't like to use RollOptions as predicates. Go figure (might be a bug lol). Since this was behavior for the legacy version, I don't feel there should be any rush to finding a solution to this.
### Poisoner
You can just follow the same process as above, obviously making the necessary changes, replacing `item:trait:healing` with 'item:trait:poison' and `flags.pf2e.advancedHerbalismCount` with `flags.pf2e.advancedPoisoncraftCount`. This same treatment can realistically be done with *any* alchemy archetype, like Wandering Chef.

It would really be appreciated if this got patched in for the next minor update, or if this is simply left open until the crafting overhaul goes live for the community to use, thanks!

**Comment by stwlam** [comment] 2024-09-29 09:45
Duplicate of #15647

**Closed by stwlam** 2024-09-29 09:45 UTC
Labels: duplicate
