### ISSUE TITLE
Bug: when adding any feat to the macro bar you can no longer see descriptions on character sheet.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4268] opened 2022-09-30 11:48 UTC
when you drop any feat onto the macro bar for quick use from the character sheet you cant click the description on the character sheet after its added. 

only after when you delete the macro shortcut will it work.

i tested it without modules.

**Comment by stwlam** [comment] 2022-09-30 14:14
Any feat or a skill feat?

**Comment by ThingsCouldGetDicey** [comment] 2022-09-30 14:23
any feat i tried skill feats then i tried others and same result. altho one time it did work correctly but it was random. all the other times it just didnt expand on the character sheet.

**Comment by In3luki** [comment] 2022-09-30 14:33
This is caused by the drag start workflow adding `data-item-id` to the dragged element and `ItemSummaryRenderer#activateListeners` looking for the closest element with that dataset.
I didn't have enough time to dig much deeper yet.

**Comment by CarlosFdez** [comment] 2022-10-01 04:41
Fixed by #4278

**Closed by CarlosFdez** 2022-10-01 04:41 UTC
Labels: bug
