### ISSUE TITLE
Would someone be willing to add a misidentify sections for items?

### ISSUE THREAD

**Issue by Gossetjr** [foundryvtt/pf2e#4841] opened 2022-11-16 16:28 UTC
Currently there is identified and unidentified. I was hoping someone might be willing to add a third for misidentified so that it acts as an identified item but allows the gm to label the item as something else. (Useful for crit failing.) 

Tried to do this with unidentified items and labelling them as another item but when clicked on it doesn't allow the item to be posted to chat or used.

**Comment by stwlam** [comment] 2022-11-18 13:06
Duplicate of #2579

**Closed by stwlam** 2022-11-18 13:06 UTC
Labels: duplicate
