### ISSUE TITLE
Feature Request: Add operation or option to bypass resistances.

### ISSUE THREAD

**Issue by a-hodges** [foundryvtt/pf2e#16660] opened 2024-09-24 01:04 UTC
A small number of features can reduce or bypass an enemy's resistances such as flensing slice or the investigator's strategic bypass. It would be nice to be able to automate these with conditions in the case of flensing slice or rules elements in the case of strategic bypass.

**Comment by stwlam** [comment] 2024-09-29 09:47
Duplicate of #13537

**Closed by stwlam** 2024-09-29 09:47 UTC
Labels: duplicate, iwr
