### ISSUE TITLE
Can't readily repick Ancestry, Class, Heritage or Background once chosen.

### ISSUE THREAD

**Issue by MisterCheesy** [foundryvtt/pf2e#6903] opened 2023-03-12 18:01 UTC
In the character builder you can't repick these items once chose.  You have to go over to the compendium to find the list, open it, and drag and drop from there.

Seems you could leave the + icon on each of those items to resolve this.

**Comment by stwlam** [comment] 2023-03-12 18:05
Duplicate of #5850

**Closed** 2023-03-12 18:05 UTC
Labels: duplicate
