### ISSUE TITLE
PC2 alchemist no worky how PC2 say it do

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/pf2e#15647] opened 2024-07-30 22:13 UTC
future issue preemption

**Comment by ammalagonc** [comment] 2024-07-31 22:40
This affects:

- [ ] Alchemist
- [ ] Alchemist Dedication
- [ ] Herbalist Dedication
- [ ] Poisoner Dedication

**Comment by MrVauxs** [comment] 2024-08-01 16:00
- [ ] Investigator (Alchemical Sciences)

**Comment by simonward** [comment] 2024-08-01 20:19
- [ ] Gunslinger Munitions Crafter

**Comment by jesuisfrog** [comment] 2024-08-01 23:51
No versatile vial bombs seem to be in the system

**Comment by JonWaterfall** [comment] 2024-08-08 19:22
As far as I can tell, daily crafting with batches is no longer a thing.
one way to fix would be to change the numeric value here: https://github.com/foundryvtt/pf2e/blob/65aaad5927d9d659c1ab8818968fd038681cd0e9/src/module/rules/rule-element/crafting/entry.ts#L51
alternative would be a rewrite or allow overriding via rule element

**Comment by aremedis** [comment] 2024-08-09 15:58
Shouldn't this be more of a "data gap" or "bug" than a "feature request"

**Comment by jesuisfrog** [comment] 2024-08-22 21:16
I'm going to try and tackle this one, if there is a comprehensive list of the feature gap, please do share to make it easier.

**Comment by ammalagonc** [comment] 2024-08-23 15:45
- [ ] apply item bonus directly on Versatile Vials (#16201)

**Comment by jesuisfrog** [comment] 2024-08-24 01:24
Nevermind, work is being done on the crafting overhaul and PRs won't be accepted for fixes at the moment.

**Comment by shemetz** [comment] 2024-08-26 06:14
![image](https://github.com/user-attachments/assets/f56d17e4-c6a5-495d-b061-8df32a76224f)

Not sure if part of this issue or a new issue, but:  the Additive trait has not been updated, even though feats using it have been.  Instead of being "Additive 2" for example, it should just say "Additive", and its new description should be put in place.

**Comment by David-Moreland** [comment] 2024-10-30 11:03
Is there any update on this issue ?

**Comment by rorp24** [comment] 2024-11-19 21:33
It as been almost 6 month since PC2 has been released, I think that before going on implementing new books, devs should focus on making sure everything already their is implemented correctly.

**Comment by samgrieve** [comment] 2024-11-19 21:35
> It as been almost 6 month since PC2 has been released, I think that before going on implementing new books, devs should focus on making sure everything already their is implemented correctly.

Dude, these are volunteers making this for free. All of whom with day jobs, families, hobbies. Entitlement doesn't tend to look great in these situations. It's coming, it's being worked on, it is discussed near daily in the discord server if you want updates.

**Comment by samgrieve** [comment] 2024-11-19 21:38
Also just to add, if you desperately want things now it's pretty workable via a couple of rule effects and a macro for Quick Alchemy. But honestly, just let the team do their thing.

**Comment by CarlosFdez** [comment] 2024-11-19 23:04
> It as been almost 6 month since PC2 has been released, I think that before going on implementing new books, devs should focus on making sure everything already their is implemented correctly.

It would be pretty funny if I told everyone else, who can't contribute to the crafting stuff at this time because its mostly a code change, to stop and do nothing while I continue to churn away at it bit by bit. Like, imagine if the new premium modules couldn't release, and people had to wait at least 2 months to play whatever AP just released? Think of the chaos!

Sure, it'd probably release about 2-3 weeks faster than currently projected, but people wouldn't be able to play any of the new stuff for months!

Personally I'd prefer if Paizo slowed down a bit.

**Comment by ottyn** [comment] 2024-11-19 23:25
All good Supe!  Been watching the commits you have been putting in on the crafting system and it's coming along great.  Most of us understand it's a huge project to rewrite it all and really appreciate all the work you are doing!

**Comment by thejoester** [comment] 2024-11-20 03:10
> > It as been almost 6 month since PC2 has been released, I think that before going on implementing new books, devs should focus on making sure everything already their is implemented correctly.
> 
> Dude, these are volunteers making this for free. All of whom with day jobs, families, hobbies. Entitlement doesn't tend to look great in these situations. It's coming, it's being worked on, it is discussed near daily in the discord server if you want updates.

We are all appreciative of the awesome work being done. That doesn’t mean we can’t question or express our frustrations on why non CORE products that were released months later are done before the alchemist.

**Comment by CarlosFdez** [comment] 2024-11-20 03:19
> > > It as been almost 6 month since PC2 has been released, I think that before going on implementing new books, devs should focus on making sure everything already their is implemented correctly.
> > 
> > 
> > Dude, these are volunteers making this for free. All of whom with day jobs, families, hobbies. Entitlement doesn't tend to look great in these situations. It's coming, it's being worked on, it is discussed near daily in the discord server if you want updates.
> 
> We are all appreciative of the awesome work being done. That doesn’t mean we can’t question or express our frustrations on why non CORE products that were released months later are done before the alchemist.

Lets ignore the monetary reason which is that there are actual products being sold using the "non CORE products", and that you're suggesting we roadblock premium modules from releasing.

Its because data entry is done by people manually inputting data, and alchemist requires programming work. The people working on the "non-core" stuff are not able to work on alchemist. That's me working on it, and I'm not full time. Nor have I been commissioned to do it and I have a day job. Different groups of people.

It doesn't help that the current existing crafting implementation is built out of toothpicks and bubblegum and is taking a lot of time to fix.

**Comment by thejoester** [comment] 2024-11-20 03:22
That’s a perfectly reasonable answer, and it makes sense. I am just saying to those answering with nasty responses (not you) attacking those who ask and calling them entitled and such - it’s not an unfair question to wonder. Now we know, at least those in this thread.

**Comment by CarlosFdez** [comment] 2024-11-20 03:24
No problem. For context, I think its people who are watching the pull requests and seeing I've been slaving away at it for a few months. Next release at least has advanced alchemy working for the archetypes, but quick alchemy is going to take a bit more work.

This won't go out for a while yet but this is my current progress:

![image](https://github.com/user-attachments/assets/d729a46c-8f5c-4ad4-8b07-fb89692c9a80)

**Comment by rorp24** [comment] 2024-11-21 16:41
@CarlosFdez Hey, just wanted to tell that advanced alchemy seems to work as intended on archetype (except for the fact that to make the same item multiple times you have to drag and drop it multiple times, which is annoying). Can't wait to have it on alchemist.

**Comment by CarlosFdez** [comment] 2024-11-22 04:11
While I think that the UX issue will be mostly resolved if we have drag/drop functional, quantity increasing/decreasing is only for infused reagents currently and I'd like to have it functional for the rest. I'll try to think of something.

**Comment by Peach774** [comment] 2024-11-28 01:53
@CarlosFdez IDK if this is a you problem, but even though advanced alchemy is working, munitions crafting doesn't seem to be? Like, bullets are crafted as single items instead of in units of 10.

**Comment by CarlosFdez** [comment] 2024-11-28 02:23
> @CarlosFdez IDK if this is a you problem, but even though advanced alchemy is working, munitions crafting doesn't seem to be? Like, bullets are crafted as single items instead of in units of 10.

That was a bug. Should be fixed by https://github.com/foundryvtt/pf2e/pull/17516

**Comment by CarlosFdez** [comment] 2024-12-16 22:01
Alchemist now worky like PC2 say it do

**Closed by CarlosFdez** 2024-12-16 22:01 UTC
Labels: feature request
