### ISSUE TITLE
Bug: Infused Reagent count on crafting tab is using pre-remaster rules

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/pf2e#16668] opened 2024-09-24 19:45 UTC
## Summary
The crafting tab for the Alchemist uses the pre-remaster calculation for Advanced Alchemy's infused reagents. It uses the Level + INT calculation, rather than 4 + INT calculation.

This also means that the feat Efficient Alchemy has no effect on that value.

## Replication
1. Create a new actor and assign the Alchemist class to it (any Research Field)
2. Change the INT modifier to +4 through manual entry or applying boosts
3. Change the level to 5
4. In the crafting tab the Infused Reagents field reads 0/9, where it should be 0/8 (4 + INT)
5. Add the 4th level Efficient Alchemy feat.
6. The number of Infused Reagents still reads 0/9, where it should be 0/10 (6 + INT)

## Notes
The `Advanced Alchemy` class feature has the following value for its effect:
```
{
  "key":"ActiveEffectLike",
  "mode":"upgrade",
  "path":"system.resources.crafting.infusedReagents.max",
  "predicate":["class:alchemist"],
  "value":"@actor.level + @actor.abilities.int.mod"
}
```
I suspect the `value` should be `4 + @actor.abilities.int.mod`.

The Efficient Alchemy feat has no rules associated with it to modify this value.

**Comment by pedrogrullada** [comment] 2024-09-24 19:56
Duplicate of  #15647

**Closed by pedrogrullada** 2024-09-24 19:56 UTC
