### ISSUE TITLE
Barbarian: Furious Footfalls Incorrectly Doubles the Hunter Automaton Speed Bonus

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/pf2e#15826] opened 2024-08-05 18:07 UTC
The Furious Footfalls barbarian feature incorrectly combines with the Hunter Automaton speed bonus. 

## Reproduction
1. Create a new Player Character actor
2. Give them the Automaton ancestry (Small or Medium)
3. Give them the Hunter Automaton heritage
4. Give them the Barbarian class
5. Level them up to Level 3 so that gain the Furious Footfalls 
6. Rage
7. The "Running on All Fours" bonus to land speed increases from +5 to +10

![image](https://github.com/user-attachments/assets/bd2bb786-3b21-4880-8e8b-f79ffb446a5f)

**Comment by pedrogrullada** [comment] 2024-08-05 18:08
Duplicate of #15692

**Closed by pedrogrullada** 2024-08-05 18:08 UTC
