### ISSUE TITLE
Elemental Ammunition not automated with rule element

### ISSUE THREAD

**Issue by yjeroen** [foundryvtt/pf2e#15439] opened 2024-07-14 16:39 UTC
![image](https://github.com/user-attachments/assets/1397c343-58e3-41ac-87c3-e489af505cc4)

![image](https://github.com/user-attachments/assets/d81e1d5a-c3c1-4043-b671-adac4c6b271a)

![image](https://github.com/user-attachments/assets/cae91728-d9de-4e30-9d05-676e3f9128e8)

Foundry 12.328
PF2e 6.0.4

**Comment by yjeroen** [comment] 2024-07-14 18:40
Also, there should be multiple formulas in the compendium, not just one generic one. :)

**Comment by websterguy** [comment] 2024-07-15 06:55
#6641

**Comment by stwlam** [comment] 2024-07-15 09:03
Duplicate of #6641

**Closed by stwlam** 2024-07-15 09:03 UTC
Labels: duplicate, feature request
