### ISSUE TITLE
Moderate Lore Curse (for oracle) should apply the Flat-Footed condition

### ISSUE THREAD

**Issue by mullr** [foundryvtt/pf2e#3536] opened 2022-08-16 06:26 UTC
I have fixed it locally by adding this rule element: 
```
{"key":"GrantItem","uuid":"Compendium.pf2e.conditionitems.AJh5ex99aV6VTggg","predicate":{"all":["self:curse:moderate"]}}
```

but clearly that may not be the right solution.

**Comment by TikaelSol** [comment] 2022-08-18 23:14
We cannot grant item conditions in the system itself, the code is not stable enough to do it as something proper and that wasn't what GrantItem was intended to do.

Closing as a duplicate of #1455

**Closed by TikaelSol** 2022-08-18 23:14 UTC
