### ISSUE TITLE
Multiple bonuses to saving throws via predicates do not stack correctly

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#4869] opened 2022-11-19 05:27 UTC
I have attached a sample effect.

It provides two RollOption checkboxes.
1: "+1 circumstance to saving throws"
2: "+2 circumstance to reflex saving throws"

Expectation:
A) no boxes: no bonus to saving throws
B) box 1 only: Fortitude, Reflex, and Will saving throws get +1.
C) box 2 only: Reflex saving throws get +2.
D) both boxes: Fortitude and Will saving throws get +1, Reflex saving throws get +2.

Actual results:
A) Saving throws are correct. However, Reflex indicates a +1 is included even though it is not.
B) Fortitude and Will saving throws get +1. Reflex should have +1 but it does not. Reflex indicates a +1 is included even though it is not.
C) Reflex saving throws get +2. Reflex indicates a +1 is included even though it is not.
D) Fortitude and Will saving throws get +1, Reflex saving throws get +2. Reflex indicates a +1 is included even though it is not.

(rename to json)
[effect-test-overlap.txt](https://github.com/foundryvtt/pf2e/files/10046148/effect-test-overlap.txt)

<img width="420" alt="Screen Shot 2022-11-18 at 9 10 26 PM" src="https://user-images.githubusercontent.com/1904698/202835906-01c6e92a-6366-4947-bea4-1802148ce726.png">

<img width="555" alt="Screen Shot 2022-11-18 at 9 28 10 PM" src="https://user-images.githubusercontent.com/1904698/202835968-4b167849-2d9d-4223-b844-c5c02f4272c4.png">

**Comment by TMunsie** [comment] 2022-11-19 05:40
You've overloaded the effect. You have the domain set as all, when really it should be set to saving-throw. This won't affect anything other than every other roll will look for this roll option unnecessarily. It isn't a problem, just bad practice.

You set the first flat modifier to multiple for no reason. It should have been single as a selector. Again, didn't break anything, just bad practice.

What you did do wrong is that you didn't have a label that was different for each flat modifier. Fill the boxes with "save all" and "save reflex" or "test 1" and "test 2" and everything works as expected.

Closing as not a bug. Working correct JSON attached.

[fvtt-Item-effect_-test-overlap.json.txt](https://github.com/foundryvtt/pf2e/files/10046162/fvtt-Item-effect_-test-overlap.json.txt)

**Closed by TMunsie** 2022-11-19 05:40 UTC
Labels: nonrepro, wontfix

**Comment by simonward** [comment] 2022-11-19 06:03
Ah, thank you! The label was indeed the issue.

The other stuff was just cruft from assembling a test case.

**Comment by stwlam** [comment] 2022-11-19 06:11
I'm guessing you edited the effect after taking the screenshots without realizing it, because the file you posted wouldn't produce what you show there.

**Comment by simonward** [comment] 2022-11-19 17:37
> I'm guessing you edited the effect after taking the screenshots without realizing it, because the file you posted wouldn't produce what you show there.

I restored my original effect, and it produces the effect shown in the screenshots. What did you expect it to do?
