### ISSUE TITLE
Feature Request: Damage Taken Dialog

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#12522] opened 2023-12-26 18:08 UTC
Much like the damage dealt dialog was recently added, updating the dialog that appears when you shift-click the damage button in the chat log would be useful.  In place of just a flat +/- number, it should have toggles for all the IWR elements as well as adding/removing flat damage of certain type.  

This would be helpful for such things as Monk's Flurry (where the damages should be combined before applying resistances, but not weaknesses, so the second instance of damage would just turn off resistances).

**Comment by stwlam** [comment] 2023-12-27 00:46
Duplicate of #11615

**Closed by stwlam** 2023-12-27 00:46 UTC
Labels: duplicate, feature request
