### ISSUE TITLE
Sneak attack triggering when source is off guard

### ISSUE THREAD

**Issue by raynboez** [foundryvtt/pf2e#9946] opened 2023-09-08 09:14 UTC
Ran into an issue where rogue sneak attack is triggering when the rogue has the off-guard effect, even though the target isn't off guard and is not a valid sneak attack target (not flanking, no surprise attack etc).

When inspecting the rolls, the attack-roll has the expected self:condition:off-guard roll option. The damage roll also has self:condition:off-guard, but target:condition:off-guard also appears. 

This issue is repeatable on off-guard NPC tokens attacking player tokens, as well as non-rogue characters attacking NPC tokens.
A non-off guard player character attacking an off-guard token has the expected behaviour (target:condition:off-guard on inspect damage roll, no self:condition:off-guard).

This was tested on a brand new world with no modules active.

**Comment by TikaelSol** [comment] 2023-09-08 14:53
I can't reproduce the issue, which means it may already be fixed in the dev build.

**Comment by stwlam** [comment] 2023-09-13 05:14
Foundry/system versions?

**Comment by raynboez** [comment] 2023-09-13 09:03
Foundry v11.308
PF2e v5.4.4

I've reinstalled the Pathfinder game system to check whether it was an issue with that, but it persisted over installs.

**Closed** 2023-09-19 04:28 UTC
Labels: bug, nonrepro
