### ISSUE TITLE
Base Weapon Types not Selectable

### ISSUE THREAD

**Issue by Sefotron** [foundryvtt/pf2e#7254] opened 2023-04-02 09:14 UTC
If you create a new weapon, using a new base weapon type you have made, it instantly unselects (or does not show as selected). 
![Screenshot 2023-03-30 121938](https://user-images.githubusercontent.com/129655725/229343669-b5d884ed-0087-4904-ae0c-c5e5908e0301.png)
![Screenshot 2023-03-30 122003](https://user-images.githubusercontent.com/129655725/229343681-7759f4b6-1fc2-4d01-b395-5bbb66b0120f.png)
![Screenshot 2023-03-30 122020](https://user-images.githubusercontent.com/129655725/229343691-031801bc-a581-4ad5-8b21-a4489fa09271.png)

**Comment by stwlam** [comment] 2023-04-02 10:02
Duplicate of #7234

**Closed by stwlam** 2023-04-02 10:02 UTC
Labels: duplicate
