### ISSUE TITLE
Armor Class Modifier menu non-functional

### ISSUE THREAD

**Issue by Bhalandros** [foundryvtt/pf2e#12816] opened 2024-01-07 11:47 UTC
The button to show where each AC modifier comes from does not work. The one for Hit Points works just fine. No modules active, other than **Find the Culprit!** which I used in order to disable said modules.
![AC mod](https://github.com/foundryvtt/pf2e/assets/27706374/7cd450e3-f794-4f28-abd9-f3f30d7ae225)

**Comment by CarlosFdez** [comment] 2024-01-07 11:59
Duplicate of https://github.com/foundryvtt/pf2e/issues/12813. Lucky for you, its resolved for next patch!

**Closed by CarlosFdez** 2024-01-07 11:59 UTC
