### ISSUE TITLE
Scroll Thaumaturgy Not Working (Solved), but now a Feature Request

### ISSUE THREAD

**Issue by DirtyLaundry6** [foundryvtt/pf2e#7027] opened 2023-03-18 12:36 UTC
Hi,
So, I'm getting an error notification when I try to use a scroll with a Thaumaturge with the Scroll Thaumaturgy Feat.
![scrollthaumaturgyerror](https://user-images.githubusercontent.com/128228797/226106388-9573a75c-c8d4-4f76-816f-ebcea4683d55.png)

Things I've tested:

1. Disabling all of my mods.
2. Trying the Use Wand or Scroll macro from Workbench.
3. Several different scrolls at different levels.
4. Reset the character to zero, then back again.
5. Created a new test Thaumaturge Actor.
6. Made sure the scroll was being held in the character's hand.
7. Sharing my screen and walking through it all with a more experienced Foundry user.

*Note: I'm a new Foundry user switching my campaign over, so I have no experience for when/ if this worked correctly. I'm using the latest version of the system.

**Update**: With some help, I figured out the problem. You have to create a Spellcasting entry for the character. So, I suppose this is now a feature request? I feel like other new users are going to be tripped up by this, so it'd be great if the system automatically created the entry for a character when they select Scroll Thaumaturgy.

**Comment by TikaelSol** [comment] 2023-03-18 16:03
Duplicate of #4882

**Closed by TikaelSol** 2023-03-18 16:03 UTC
