### ISSUE TITLE
Bestial Mutagen - effect error

### ISSUE THREAD

**Issue by DoctorDankovsky** [foundryvtt/pf2e#16123] opened 2024-08-19 12:43 UTC
Bestial Mutagen effects added rules for feat Mutant Physique, but they seem to overwrite the old rules, and a character without that feat stops getting unarmed attacks from the mutagen effect.

**Comment by pedrogrullada** [comment] 2024-08-19 14:32
Duplicate of #16090

**Closed** 2024-08-19 14:32 UTC
Labels: pr: data update
