### ISSUE TITLE
FR: please change size of template if modified by something else on the place template button

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#15658] opened 2024-07-31 22:45 UTC
one of my players pointed out that while they are playing a oscilating wave psychic they modify redistribute potential via an amp but the place button doesnt change to the new modification of the size. which should be two 10 ft bursts. 

![image](https://github.com/user-attachments/assets/ba1cb140-4457-4676-9b71-5aecdc7f33e3)

even tho it is amped it should have place 10 foot burst. 

this isnt only isolated to the oscilating wave psychic, this would be affected by spell shape feats, and spells and feats that modify size changes.

**Comment by pedrogrullada** [comment] 2024-07-31 22:47
Duplicate of #14023 and tracked in #15579

**Closed by pedrogrullada** 2024-07-31 22:47 UTC
