### ISSUE TITLE
Magic Missile and Dangerous Sorcery

### ISSUE THREAD

**Issue by Bam4k** [foundryvtt/pf2e#5433] opened 2023-01-02 03:55 UTC
### User Experience

Because you do not control at what level or how many actions you use when you cast magic missile when it interacts with the Sorceror class feat Dangerous Sorcery (that adds the spells level to damage) it does so every single time you generate damage. Dangerous Sorcery damage that should only occur once during the spell instead occur everytime you roll damage, ultimately doing more damage than intended.

**Comment by aaclayton** [comment] 2023-01-02 16:22
Closing as duplicate of https://github.com/foundryvtt/pf2e/issues/5426

**Closed by aaclayton** 2023-01-02 16:22 UTC
