### ISSUE TITLE
Feature Request: add spells tab to hazards that need it

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#14998] opened 2024-06-06 23:06 UTC
i have an issue with hazards that are usually complex and higher level. in the description you have "it casts X spell heigtened to X level" the problem that occurs from this is theres no reference to roll damage or a spell to reference. you have to manually look up the spell. make sure the damage values are correct and then somehow apply the correct energy damage every time to multiple pcs. 

what i propose is a spells tab that when cast, doesnt decrease the spell slots but does the correct specified damage if it was heigtened or not. 

if that isnt possible i would even settle for when these get data entried for them to have a rollable damage in the description thats correct with its energy damage. 

here is why i came across this issue 
![image](https://github.com/foundryvtt/pf2e/assets/62528192/a62b1265-dba1-4f60-a6b9-fd8434d3097d)
if you check you can see a link to the spell but theres no where to cast the correct amount of damage.

**Comment by stwlam** [comment] 2024-06-07 01:29
Duplicate of #585

**Closed by stwlam** 2024-06-07 01:29 UTC
Labels: duplicate
