### ISSUE TITLE
[Bug] Spell chat messages generated from scrolls and wands don't work.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#11583] opened 2023-11-19 14:27 UTC
Title

Use a wand or scroll on a characters sheet, it will generate a chat message but the chat message is broken.
![image](https://github.com/foundryvtt/pf2e/assets/49882452/18e218cd-09a2-4bad-bfbb-03cebcb73ec7)

**Comment by simonward** [comment] 2023-11-19 17:06
Duplicate of https://github.com/foundryvtt/pf2e/issues/11453

**Closed by simonward** 2023-11-19 17:06 UTC
Labels: duplicate
