### ISSUE TITLE
Add "removeAfterRoll" to DamageDice

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#14783] opened 2024-05-20 22:14 UTC
As title. Currently adding `"removeAfterRoll": "if-enabled",` in a DamageDice RE inside of an effect does not result in that effect being removed after rolling damage with the rule enabled.

**Comment by stwlam** [comment] 2024-05-20 22:39
Duplicate of #10831

**Closed by stwlam** 2024-05-20 22:39 UTC
Labels: duplicate
