### ISSUE TITLE
Feats with Stat Requirements show as not qualified for

### ISSUE THREAD

**Issue by Jeramiahh** [foundryvtt/pf2e#10755] opened 2023-10-15 21:38 UTC
Fairly simple one - with the Remaster removing base stats in favor of just the bonus, feats that require a certain attribute show as not being qualified for - for instance, the one we found was Intimidating Prowess, which requires a Str of 16, but didn't show up for the 18 Str Barbarian - because they have a +4 Str, not an 18 any more.

I figure this'll be addressed when Player Core arrives, but I figured it'd be a good one to have tracked.

**Comment by stwlam** [comment] 2023-10-15 22:13
Prerequisites aren't enforced: they're just unstructured text.

**Comment by Jeramiahh** [comment] 2023-10-15 22:16
Not enforced, no, but they don't show up in the list of 'feats you qualify for' when searching in the Compendium Browser. This led to a very confused new player who was trying to find and add Intimidating Prowess, and found that it wasn't an option for her - and a briefly confused long-time GM, who quickly identified the problem as listed above.

**Comment by stwlam** [comment] 2023-10-15 22:17
Duplicate of #10750

**Closed by stwlam** 2023-10-15 22:17 UTC
Labels: bug, duplicate
