### ISSUE TITLE
Some monster info is cut off on left side in cases where it is long

### ISSUE THREAD

**Issue by fishrobe** [foundryvtt/pf2e#16365] opened 2024-09-01 15:03 UTC
As the title, some monsters with lots of info on the left pannel seem to get cut off now (I don't know when this started but I don't remember it happening before). Expanding the window doesn't help, as the left bar doesn't change size. In the example, the only way to see what stops its fast healing is to import it, then click on it to edit and manually scroll to the end. EDIT: I should add that this is with all modules deactivated.
![info cut off foundry](https://github.com/user-attachments/assets/16aea8fb-48aa-4a3a-8171-52299a38c427)

**Comment by ammalagonc** [comment] 2024-09-01 15:50
Hey there, 

I tried recreating the issue in the Native client and via web browser - nada.

If you create a new world, do you still experience this issue?

**Comment by TikaelSol** [comment] 2024-09-01 20:05
If you mean the HP details and whatnot, that's normal and there's already an issue for it. If you mean the initiative selector then the reason is because there's a long skill name expanding the box, which is undesirable but not common.

**Comment by fishrobe** [comment] 2024-09-01 23:02
> If you mean the HP details and whatnot, that's normal and there's already an issue for it. If you mean the initiative selector then the reason is because there's a long skill name expanding the box, which is undesirable but not common.

No I just mean under "Temp" the Regeneration 40 line is cut off with no way to expand it. I am starting up Foundry to make a new world now to check it.

**Comment by fishrobe** [comment] 2024-09-01 23:19
> Hey there,
> 
> I tried recreating the issue in the Native client and via web browser - nada.
> 
> If you create a new world, do you still experience this issue?

Still happening in a brand new world with 0 modules activated. 
![misery 2](https://github.com/user-attachments/assets/3cbbe387-c1c9-4b0b-a8cd-249f76124833)

**Comment by TikaelSol** [comment] 2024-09-03 22:34
Right, it's not a bug, That's just how those fields are for now. Closing as a duplicate

**Closed by TikaelSol** 2024-09-03 22:34 UTC
Labels: duplicate
