### ISSUE TITLE
"Advanced X" Feats Missing Choice Set

### ISSUE THREAD

**Issue by Spyker222000** [foundryvtt/pf2e#5667] opened 2023-01-13 02:41 UTC
The Advanced series of archetype feats (e.g., Advanced Trickery, Advanced Fury, Advanced Shooting, etc.) seem to be missing their Choice Set and Grant Item rules.  They should work similarly to the Basic series (e.g., Basic Trickery, Basic Fury) but with a feat equivalent of half the character's level.  An example of the feat text is here: https://2e.aonprd.com/Feats.aspx?ID=674

**Comment by TikaelSol** [comment] 2023-01-13 05:09
Duplicate of #1956, closing

**Closed by TikaelSol** 2023-01-13 05:09 UTC
