### ISSUE TITLE
Feature Request: a dedicated area on neutral npcs for influence and attitude.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#14292] opened 2024-03-25 12:35 UTC
the issue i have is im running kingmaker and in the first part of the adventure you have 10 people with influence stat blocks and it makes it difficult to track. 

what i propose is a solution that enables areas on npcs that are of neutral alignment to have an area for attitude and influence. 

and for npcs to have the inline checks stored on the actor sheet. 

then have pips i.e circles that could be filled by the gm based on how many the pcs need based on the stat block requirements. 

what would also be useful is to have a way to globally change the checks needed against them for these results as often in aps if the players do something they can get a bonus or penalty against the inline checks. 

The other request would be to have a drop down menu that the gm could control with the attitude. so that the gm could select the influence based on rolls.

**Comment by stwlam** [comment] 2024-03-29 19:31
Duplicate of #4222

**Closed by stwlam** 2024-03-29 19:31 UTC
Labels: duplicate, feature request
