### ISSUE TITLE
Create a function to deal damage derived from a message to a specific target

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#5611] opened 2023-01-09 12:17 UTC
It'd be beneficial to create an open `applyDamageFromMessage` function available to macros and modules (such as PF2e Target Damage) that allows to deal damage based on a messages contents, to a specific array of tokens.

https://github.com/foundryvtt/pf2e/blob/43c3e9b3663deaaa3986a4b939608a00b834bea9/src/module/chat-message/helpers.ts#L11-L41

Also with the last few updates, the function to apply damage has constantly been changed requiring updates on the behalf of said modules and macros, and will likely need to be updated further with more improvements to the damage system. It'd be great if we could just rely on the system implementation instead of having to copy the code over from the latest version.

Lastly, I think the system would benefit from putting `tokens` as an argument that simply defaults to being selected, rather than being hard-coded to only be that.

**Comment by CarlosFdez** [comment] 2023-01-09 12:22
Looking at it, it seems like maybe the ways to alter damage (the shift apply damage and roll.alter()) could maybe be simpler api wise. Though I suspect perhaps this is something that may or may not  wanna wait until fixing double damage dice for maybe.

Other than that, not really too much here that's unique.

**Comment by stwlam** [comment] 2023-01-09 22:03
Duplicate of #3556

**Closed by stwlam** 2023-01-09 22:03 UTC
Labels: duplicate, feature request
