### ISSUE TITLE
Feature Request: Increase effective emanation radius with creature size

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#11943] opened 2023-12-02 10:07 UTC
Currently, when you place an emanation template, the radius of the emanation does not depend on the creature size.
This makes an 5-foot emanation from a large creature cover only the creature itself.

According to https://2e.aonprd.com/Rules.aspx?ID=354, the radius of the emanation should start from the edges of the creature token.
The effective radius should increase by 5 feet for a large creature, 10 feet for a huge creature and 15 feet for a gargantuan creature.
Since this should take into account effects like the Enlarge spell, it can't be edited directly in the emanation description itself.

**Comment by stwlam** [comment] 2023-12-02 11:09
Duplicate of #630

**Closed by stwlam** 2023-12-02 11:09 UTC
Labels: duplicate
