### ISSUE TITLE
Weapon familiarity with advanced weapons doesn't work with Fighter Weapon Mastery

### ISSUE THREAD

**Issue by Deatrathias** [foundryvtt/pf2e#17194] opened 2024-11-05 09:32 UTC
So let's say I'm a dwarf fighter level 5 with Dwarven Weapon Familiarity, and axe mastery
![image](https://github.com/user-attachments/assets/1ad2fc1b-876c-4869-94ff-b2f97e3da266)
I should treat advanced dwarf weapons as martial weapons, and have master proficiency with martial axes.
However, if I try to use a Dwarven War Axe
![image](https://github.com/user-attachments/assets/c57e4b07-d834-4c11-ae26-7a3f634baa69)
I have expert proficiency and not master.

**Comment by pedrogrullada** [comment] 2024-11-05 21:09
Duplicate of #16906
We need to be able to specify a Martial Proficiency to be the same as a specific group within a category.

**Closed by pedrogrullada** 2024-11-05 21:09 UTC
