### ISSUE TITLE
Feature request: Add selected token name to the roll dialog window.

### ISSUE THREAD

**Issue by Biscolino** [foundryvtt/pf2e#14225] opened 2024-03-15 15:21 UTC
As a simple feature request I would like to have the name of the selected token listed on the roll dialog window. Either in the title or above the modifiers.

A more sophisticated (and complex?) solution would be a dropdown to the controlled tokens on the canvas? Not even sure whether this is possible.

**Comment by stwlam** [comment] 2024-03-16 02:53
Duplicate of #1384

**Closed by stwlam** 2024-03-16 02:53 UTC
Labels: duplicate, feature request
