### ISSUE TITLE
Investigator's Strategic Strike damage is no longer applied

### ISSUE THREAD

**Issue by avralash** [foundryvtt/pf2e#15844] opened 2024-08-05 23:17 UTC
After using an Attack Stratagem and having a successful attack roll, clicking "Damage" no longer applies investigators' Strategic Strike damage:

![image](https://github.com/user-attachments/assets/2a8838b3-92f2-4280-88ec-bcab12811e79)

![image](https://github.com/user-attachments/assets/43f98bb9-9e68-4ca2-a7e3-4885285418d4)

![image](https://github.com/user-attachments/assets/57e5c3e1-85a8-4a34-be1d-bf209b81a046)

Executing this workflow in previous versions would automatically add Strategic Strike Damage.

**Comment by pedrogrullada** [comment] 2024-08-05 23:18
Duplicate of #15787

**Closed by pedrogrullada** 2024-08-05 23:18 UTC

**Comment by avralash** [comment] 2024-08-06 00:17
thank you! I couldn't find the duplicate for whatever reason. I appreciate y'all!
