### ISSUE TITLE
PC2 : Incorrect number of infused reagents from Advanced Alchemy

### ISSUE THREAD

**Issue by MythicCat** [foundryvtt/pf2e#15813] opened 2024-08-05 08:04 UTC
**Advanced Alchemy** has a wrong formula for calculating number of infused reagents.
Current formula is [ **Level + Int mod** ] for Alchemists and [ **Level** ] for non-alchemist.
Correct formula is [ **4 + Int mod** ] for Alchemist and [ **4** ] for Alchemist Dedication with Advanced Alchemy (Feat 4)
**Alchemist class feature:**
![image](https://github.com/user-attachments/assets/58338d82-a7c2-4ec4-8183-96973868ac95)

**Alchemist dedication Feat:**
![image](https://github.com/user-attachments/assets/960313ed-d095-4c98-b894-a061aa4076c5)

**Comment by stwlam** [comment] 2024-08-05 09:36
Duplicate of #15647

**Closed by stwlam** 2024-08-05 09:36 UTC
Labels: duplicate
