### ISSUE TITLE
Request: Character sheet for companions 

### ISSUE THREAD

**Issue by Brandoff1392** [foundryvtt/pf2e#5746] opened 2023-01-15 20:37 UTC
Maybe a new sheet similar to the familiar sheet, but for companions.

**Comment by simonward** [comment] 2023-01-15 20:48
In the meantime, try out PF2e Companion Compendia:
https://foundryvtt.com/packages/pf2e-animal-companions

**Comment by Brandoff1392** [comment] 2023-01-15 20:53
Ok i will definitely check this out. Thank you

**Comment by TMunsie** [comment] 2023-01-15 20:56
Closing as Duplicate of #802

**Closed by TMunsie** 2023-01-15 20:56 UTC
