### ISSUE TITLE
Swaggering Initiative should be "on" by default

### ISSUE THREAD

**Issue by johncarney** [foundryvtt/pf2e#11600] opened 2023-11-19 23:28 UTC
When a character has taken the [_Swaggering Initiative_](https://2e.aonprd.com/Feats.aspx?ID=1531) feat, they should always get a +2 circumstance bonus to their initiative roll. However, the _Flat Modifier_ rule element on the feat has a `swaggering-initiative` predicate, but no corresponding _Roll Option_ element. Meaning the circumstance bonus is inactive by default.

The `swaggering-initiative` predicate should be removed from the feat's _Flat Modifier_ rule element.

<img width="735" alt="image" src="https://github.com/foundryvtt/pf2e/assets/322950/6f098165-4966-491f-b79a-819e4acc8b89">
<img width="376" alt="image" src="https://github.com/foundryvtt/pf2e/assets/322950/504f1af1-b679-4969-9926-42a1e63452d8">

**Comment by stwlam** [comment] 2023-11-19 23:37
Duplicate of #11014

**Closed by stwlam** 2023-11-19 23:37 UTC
Labels: duplicate
