### ISSUE TITLE
Oak potion is clunky to use

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#13689] opened 2024-02-12 01:58 UTC
Foundry VTT: 11
Build: 315
PF 2e version: 5.13.6

When using the potion "Oak Potion" all that comes up is "Uses Oak Potion."

Dragging "Oaken Resilience" within the text description for the potion has no effect either. The proper way to use it is to: Open the potion, within the description click on "Oaken Resilience" then drag "Spell Effect: Oaken Resilience" onto the effected token.

Like I said, it's more clunky to use then other potions/elixirs. Since when those are used, there is a dialog box of it being used and what effect it causes.

**Comment by TikaelSol** [comment] 2024-02-15 03:09
Closing as a duplicate of #2103

**Closed by TikaelSol** 2024-02-15 03:09 UTC
Labels: data other
