### ISSUE TITLE
Spells missing

### ISSUE THREAD

**Issue by tnanek** [foundryvtt/pf2e#9588] opened 2023-08-26 13:56 UTC
So, I'm on Foundry v11 stable, build 307.

Just updated modules the other day, and since, no one in my game has access to spells.

Now I also have Oracles+ installed, and those spells list just fine, I also have 2 other spells on my list, namely Produce Flame (Dust to Dust) from the core book, and from the Dark Archive Time Sense (Temporal Flux). I don't know what's going on, and my party just leveled up last session, so they need to access the spells.

**Comment by TMunsie** [comment] 2023-08-26 14:18
So, this isn't really a bug report so much as a need for troubleshooting. Please try using the discord first unless this is a reproducible bug.

Have you tried uninstalling and reinstalling the PF2e system? The biggest issue is generally that Foundry doesn't natively do any error checking, and with a system this size there is always a chance (and it usually turns out to be the case) of a bad install. You may need to fully remove the system from the system folder (this won't affect your worlds) after uninstalling from the interface.

Have you checked that you don't see the spell compendium as the GM, and that you haven't disabled the sources in the browser or hidden the spell compendium from the players?

In any case, closing as non-reproducable. If these steps don't work please come and ask on #pf2e in the foundry discord or in #troubleshooting on the community discord.

**Closed by TMunsie** 2023-08-26 14:18 UTC
Labels: nonrepro, wontfix
