### ISSUE TITLE
Suggestion: Better sorting options on the character sheet for Inventory and various lists.

### ISSUE THREAD

**Issue by Wizard-Level-1** [foundryvtt/pf2e#5972] opened 2023-01-27 22:46 UTC
I made this suggestion in the official foundry server, but I thought it might be relevant to post it here as well in case some or all of this stuff can be implemented without any changes to Foundry core.

Firstly,  The crafting section Has no way to sort by item type (bomb, elixir etc.), nor does it even allow one to drag things where you want for manual sorting (like you can for the inventory). Potions, bombs, ammo, everything is just thrown all together; it isn't even alphabetical. To start I'd like to be able to drag formulas in the crafting section around so I can at least group like items with like.  

For future improvements beyond that, It might be nice to add (collapsible) sections within the crafting levels as well so one could further keep their formulas sorted and make it easier to find what they are looking for by keeping certain sections collapsed until they need them.  It is possible to have dozens and dozens of formulas of a given level and without sorting and organization options many of us are just flailing about during our daily preparations looking for that one thing while everyone else is ready to get back to the dungeon.

Secondly, the inventory. Right now inventory sections are static: weapons, armor, equipment, consumables, treasure, containers. At a minimum, I would like the various sections be collapsible and moveable (like if I want to put containers at the top of the sheet and weapons or treasure at the bottom).  For future improvements I'd like to be able to move any item into any section I want, specifically containers because I might keep my consumables in a belt pouch or a bandoleer and instead of having them listed in the container in the container section I would rather have them listed in the container in the consumables section.  Creating custom sections would be nice as well, or even sub sections.  Having my consumables section broken down into elixirs, bombs, mutagens ect would be very helpful.  Characters end up with dozens of items, alchemists especially, so better sorting options would be very helpful!

Lastly, I have some wish list improvements I doubt would ever be implemented but that I think would be interesting:  An inventory (and crafting) screen that has multiple columns (perhaps individual users could decide if they want to display their item list as one 2 or 3 columns.) An alternative way of displaying inventory, like a tile system where clicking on the tile could open up a dialogue box or expand the tile with the item description).

Each player being able to have more control over how their character sheet looks and where things are will help a lot with keeping the game running smooth.  DM's could override options they don't like, or have an option to have character sheets display to them in their preferred style (client-side display settings.)

 There is no better place to play pathfinder 2, and all of you working on this are real heros in this community.  Hopefully some of my suggestions will spark some interest, if not thanks for everything you do anyway.

**Comment by stwlam** [comment] 2023-02-05 22:53
Duplicate of #1152

**Closed by stwlam** 2023-02-05 22:53 UTC
