### ISSUE TITLE
Advanced Mystification Feature Request

### ISSUE THREAD

**Issue by Xelalego** [foundryvtt/pf2e#3093] opened 2022-07-23 21:19 UTC
The current Mystification is good, but it is also overly simple.  According to PF2e identification rules, a regular success only reveals the activation methods - not the actual effects of those actions, and a critical failure misidentifies the item - which is near impossible to pull off in the moment currently.

How I would suggest implementing this:
Create 1 or 2 more Mystified tabs (or sub-tabs) which have the same functionality as Mystifying, and allow GMs to choose which version is displayed.  This way GMs can manually create simplified item descriptions which only give the information that they choose (such as the Activate requirements without the ability description, or the apparent effects of a cursed item).
Finally, for misidentifying items it would be ideal to be able to drag and drop another item onto the misidentified item (probably with a confirmation popup) and automatically set the Mystified properties to the visible properties of the other item.

EDIT:
Found existing request: #2579

**Comment by stwlam** [comment] 2022-11-18 13:07
Duplicate of #2579

**Closed by stwlam** 2022-11-18 13:07 UTC
Labels: duplicate
