### ISSUE TITLE
No way to make a familiar "Skilled"

### ISSUE THREAD

**Issue by Lemantia** [foundryvtt/pf2e#3988] opened 2022-09-15 15:26 UTC
Adding the "Skilled" ability to a familiar doesn't let us choose the skill to add the Master's ability to. 

There are no way to manually change that either.

**Comment by avagdumortesin** [comment] 2022-10-01 07:29
This is a duplicate of https://github.com/foundryvtt/pf2e/issues/3552.

**Closed** 2022-10-01 08:42 UTC
Labels: duplicate, feature request
