### ISSUE TITLE
Two creatureSize RE's with "resizeEquipment":true doubling up equipment size

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#12143] opened 2023-12-11 00:08 UTC
Pf2e version 5.10.5
Placed two creatureSize REs from Battlezoo Dragon Ancestry module on a PC (Empowered Size and Ancient's Size) end up making items dropped from compendium browser Gargantuan.
Current work around is resizing the items back to medium on the actor.
@TikaelSol said that it sounds like a system bug.

**Comment by stwlam** [comment] 2023-12-11 00:10
Duplicate of #2840

**Closed by stwlam** 2023-12-11 00:10 UTC
Labels: bug, duplicate
