### ISSUE TITLE
Compendium Browser not pre-filtering

### ISSUE THREAD

**Issue by Thedvdias** [foundryvtt/pf2e#6983] opened 2023-03-15 15:55 UTC
I've noticed that when you browse feats they don't get pre-filtered anymore. Example : I'm a dwarf and I want to browse ancestry feats. It shows all ancestry feats not only the ones with the dwarf trait.

**Comment by stwlam** [comment] 2023-03-15 15:57
Duplicate of #6947

**Closed by stwlam** 2023-03-15 15:57 UTC
Labels: duplicate
