### ISSUE TITLE
Shield Ally Effect not increasing Shield HP and BT

### ISSUE THREAD

**Issue by Unikatze** [foundryvtt/pf2e#3561] opened 2022-08-18 13:34 UTC
The effect on shield ally is correctly increasing the shield's hardness but not the HP and BT.

**Comment by TikaelSol** [comment] 2022-08-18 23:07
Not currently possible to affect the HP or BT of a shield. Closing as a duplicate of #1318

**Closed by TikaelSol** 2022-08-18 23:07 UTC
