### ISSUE TITLE
Thermal Nimbus (Kineticist Fire Impulse) missing the damage it inflicts to those that enter the aura

### ISSUE THREAD

**Issue by dyoung418** [foundryvtt/pf2e#10086] opened 2023-09-15 06:19 UTC
The Thermal Nimbus impulse is supposed to have two main effects:

- Give resistance to fire|cold (whichever is chosen) to you and allies in the aura at the kineticist's level
- Any creature that starts its turn in your kinetic aura or moves into your aura during its turn takes damage equal to half your level of the chosen type.

The latter effect is not implemented (which may be OK), but also not mentioned in the description of the effect (either on the effect page, or on the pop-up from the effect when it is on an actor).  It should be included in the description to help players remember to implement it.

**Comment by TikaelSol** [comment] 2024-01-12 07:47
Duplicate of #7123

**Closed by TikaelSol** 2024-01-12 07:47 UTC
Labels: feature request
