### ISSUE TITLE
Automatic Bonus Progression

### ISSUE THREAD

**Issue by rdsbrazil** [foundryvtt/pf2e#4944] opened 2022-11-23 21:39 UTC
using the ABP variant rule, when characters hit level 3 they gain a +1 potency bonus to a skill.

all skills have the "modifier" area under proficiency, were i can add the +1 potency.

the exception is the lore skills, they doesn't have a modifier, and they are valid choices.

**Comment by stwlam** [comment] 2022-11-24 18:27
Duplicate of #4620

**Closed by stwlam** 2022-11-24 18:27 UTC
Labels: duplicate, feature request
