### ISSUE TITLE
Compendium Browser does not reflect price for all items accurately

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#14865] opened 2024-05-28 04:38 UTC
Follow up, seems to be root cause of issue #14864. When price is automatically adjusted by system for things like the size of equipment being changed, the updated price is not reflected in the compendium browser's price display.

**Comment by stwlam** [comment] 2024-06-03 05:51
Do you have any examples?

**Comment by websterguy** [comment] 2024-06-03 06:04
Shown in linked issue, large barding has its price automatically increased to 50gp due to size increase, but compendium browser still shows 25gp. Tikael said to put up the issue so the display in the browser could be improved to reflect that.

![image](https://github.com/foundryvtt/pf2e/assets/54455090/792784a4-2b5f-4268-8519-77c1eecc13cc)

**Comment by stwlam** [comment] 2024-06-03 10:33
Duplicate of #14864

**Closed by stwlam** 2024-06-03 10:33 UTC
Labels: duplicate
