### ISSUE TITLE
Splash Damage is being multiplied for the Double Damage option

### ISSUE THREAD

**Issue by Demorome** [foundryvtt/pf2e#7641] opened 2023-05-02 01:45 UTC
According to information from the Splash trait, "You don’t multiply splash damage on a critical hit."
However, when pressing the button to apply "Double" damage, splash damage is being doubled. For effects that deal more than just splash damage, like Alchemist's Fire and Acid Splash, this makes it tricky to calculate the true damage for the target on a crit.

Here is an example of the issue, using the system's Acid Splash spell:
![image](https://user-images.githubusercontent.com/69116996/235560996-6628be8c-a4b9-46d5-b924-e448b8508279.png)

The base damage that was rolled was 3, plus 1 splash damage. On a crit, splash won't get multiplied, so it should deal (3*2) + 1 = 6 + 1 = 7 damage. However, it just does (3 + 1) * 2 = 4 * 2 = 8 damage, so it adds the splash damage in the doubling.

Since I'm not sure if there's any source that actually wants splash damage to get doubled, could this behavior be changed?

**Comment by stwlam** [comment] 2023-05-02 02:50
Duplicate of #4882

The double-damage button does exactly what it says. It doesn't know what a spell's critical damage is since that information isn't stored anywhere except in the description. In the case of strikes, critical damage should be rolled.

**Closed by stwlam** 2023-05-02 02:50 UTC
Labels: duplicate

**Comment by CarlosFdez** [comment] 2023-05-02 02:52
I think it'd be reasonable to check the metadata for the splash flavor, but given it only affects acid splash I can see the appeal of waiting till spells have variable degree of success.

**Comment by Demorome** [comment] 2023-05-02 02:54
It also affects splash damage from bombs, I tested with Alchemist's Fire.

**Comment by CarlosFdez** [comment] 2023-05-02 02:55
In the case of bombs, those are implemented. You click the critical damage button and it'll roll the correct damage. You're not supposed to use the half/double damage buttons for regular strikes (I suspect it'll go away at some point).

**Comment by Demorome** [comment] 2023-05-02 02:56
Ahhh, my bad then, sorry.
