### ISSUE TITLE
Feature Request: A button to sort equipment alphabetically within eq. categories.

### ISSUE THREAD

**Issue by SynthJackalope** [foundryvtt/pf2e#4230] opened 2022-09-28 06:09 UTC
Some sort of "sort alphabetically within categories" button in the Equipment tab on the player sheet would really help those less organised/more hoardy players. 

One of my players simply LOVES consumables and it has gotten to a stage when it's hard to find anything.
Of course, those consumables are narratively kept in a Bag of Cheating... I mean Holding, but Foundry-wise they're in the general inventory.

**Comment by zarmstrong** [comment] 2022-09-29 07:30
Additionally, all columns sortable would be great. Sort by bulk, by equipped status, etc.

**Comment by manituan** [comment] 2022-09-29 18:03
I asked in the Pf2e discord something like this. Personally, I´d love it if we could sort them by level.  
Additionally, if the level was shown in the inventory window right away would be amazing. Getting inside each object´s details to see it is very tiresome. Thanks!

**Comment by hmarthinsen** [comment] 2022-10-11 20:53
The same applies for loot/merchant sheets. It's hard for players to find items if there are a lot of them and the items aren't sorted.

**Comment by stwlam** [comment] 2023-02-05 22:51
Duplicate of #1152

**Closed by stwlam** 2023-02-05 22:51 UTC
Labels: duplicate, feature request
