### ISSUE TITLE
Add "Minimum Skill Rank" or "Trained" checkbox to Action Item Sheet

### ISSUE THREAD

**Issue by jsrose09** [foundryvtt/pf2e#12085] opened 2023-12-07 20:26 UTC
Currently, there is no indication in the Foundry Module to whether an Action requires the character to be trained or not in the relevant Skill requiring memorization of Actions or cross referencing text in the middle of play. If this feature was added and referenceable, it would also be possible to auto populate the Actions tab of the character sheets with all possible actions the player characters may use.

**Comment by stwlam** [comment] 2023-12-19 05:39
Duplicate of #1505

**Closed by stwlam** 2023-12-19 05:39 UTC
Labels: duplicate, feature request
