### ISSUE TITLE
[BUG] Equipment marked dropped doesn't reduce encumbrance

### ISSUE THREAD

**Issue by CoridanM** [foundryvtt/pf2e#9291] opened 2023-08-13 00:28 UTC
Version: 5.3.2

Issue: Marking equipment as 'dropped' on your character sheet doesn't affect your encumbrance/carry amount.

Solution: Dropped equipment should count as 0 bulk for measuring encumbrance.

**Comment by stwlam** [comment] 2023-08-13 00:32
Duplicate of #5528

**Closed by stwlam** 2023-08-13 00:32 UTC
Labels: duplicate
