### ISSUE TITLE
Oracle Focus Pool not going above 1

### ISSUE THREAD

**Issue by zwolfwood** [foundryvtt/pf2e#11853] opened 2023-11-29 05:30 UTC
For some reason Oracle focus pool cannot go higher than 1 even though it by default starts at 2 and adding feats that are supposed to increase the focus pool don't do so past 1.

Revelation Spells:
The powers of your mystery manifest in the form of revelation spells, which are a type of focus spell. Casting a revelation spell costs 1 Focus Point and increases the effects of your Oracular Curse. ___"You start with a focus pool of 2 Focus Points"___. You refill your focus pool during your daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to reconcile the conflicting or unconventional nature of your divine mystery.

**Comment by stwlam** [comment] 2023-11-29 06:11
Duplicate of #11842. Welcome to this crazy remaster world.

**Closed by stwlam** 2023-11-29 06:11 UTC
Labels: wontfix, remaster
