### ISSUE TITLE
Bug Report: Heritage's that change an Ancestry's Size don't get respected by Crafting (Items made come out Medium regardless of crafter's size)

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#10278] opened 2023-09-22 18:28 UTC
If you make a Toy Poppet, Compact Skeleton, Pixie, etc (things with Heritages that change their size) and either craft an item or do Daily Crafting, it'll make Medium items instead of whatever size you'd expect it to be.

**Comment by stwlam** [comment] 2023-09-23 15:15
Duplicate of #10256

**Closed by stwlam** 2023-09-23 15:15 UTC
Labels: duplicate

**Comment by GorgoPrimus** [comment] 2023-09-23 16:42
Alright, I won’t post on anything related to this again. But with all due respect, in my defence I thought of this as two different issues. One was a report that crafting as a Tiny PC can only ever make Medium items (which it turns out isn’t true), whereas this was a report that Tiny ancestries can make Tiny items but that heritages that change ancestry sizes in general bugged it out and made it so you could only craft Medium items (which is a reproducible cause). And neither of them seemed to me to be the same as the report you’re saying they’re duplicates of which is a request that you be allowed to make sized formulas so you can make different sized items from your character at will.
