### ISSUE TITLE
Psi Development Choice Data Error

### ISSUE THREAD

**Issue by sakusenerio** [foundryvtt/pf2e#14531] opened 2024-04-26 18:25 UTC
https://github.com/foundryvtt/pf2e/issues/14333

According to this issue, yeah surface psi cantrip can't be selected by "Psichic Dedication", that bug is fixed.
The Problem is, the fix also deleted the option for "[Psi Development](https://2e.aonprd.com/Feats.aspx?ID=3740)", which DO allow you to choose a surface psi cantrip, now whatever we do, we just can't get surface psi cantrip as a choice when getting Psi Development.

**Comment by pedrogrullada** [comment] 2024-04-26 18:26
Duplicate of #14476

**Closed** 2024-04-26 18:27 UTC
