### ISSUE TITLE
Imperial blood magic effect text

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#15776] opened 2024-08-04 11:49 UTC
text description of the effect for imperial blood magic still references old effect of boosting skill checks.
![image](https://github.com/user-attachments/assets/90d870ad-def2-4ae1-9893-cfb8548dfd35)

**Comment by ammalagonc** [comment] 2024-08-04 14:02
![image](https://github.com/user-attachments/assets/0724f70f-a11c-4aa1-ab6e-0c1905a89b9e)

Looks fine on my end. Try resetting the actor to level 0 and then back to it's original level to refresh the features.

**Comment by pedrogrullada** [comment] 2024-08-04 15:45
Duplicate of #15744 already resolved for next release

**Closed** 2024-08-04 15:45 UTC
Labels: nonrepro
