### ISSUE TITLE
Add description on feat choices or abilities choices (barbarian insctinct for example)

### ISSUE THREAD

**Issue by DixxyDix77** [foundryvtt/pf2e#9786] opened 2023-09-02 17:25 UTC
Hi !
It would be really cool if we were able to read the choices before clicking on it. Like barbarian instincts, a window pops up and ask which one you want, it would be nice if you right click or hover the name and it opens the journal with what  the instinct does before deciding. Same for the feat that gives you a general feat choice, would be nice to know what the feat does easier

**Comment by stwlam** [comment] 2023-09-03 03:24
Duplicate of #9404, but copied comment over

**Closed by stwlam** 2023-09-03 03:24 UTC
Labels: duplicate, feature request
