### ISSUE TITLE
Console Error with Token Action Hud pf2e

### ISSUE THREAD

**Issue by Monkeyking727** [foundryvtt/pf2e#8865] opened 2023-07-22 07:02 UTC
![image](https://github.com/foundryvtt/pf2e/assets/140234226/072ccb9d-b4c7-48ba-8c2f-2ad5af52ceab)

This error occurs when clicking on token

**Comment by stwlam** [comment] 2023-07-22 07:09
Duplicate of #8863

**Closed by stwlam** 2023-07-22 07:09 UTC
Labels: duplicate
