### ISSUE TITLE
Unable to reduce ability scores below 8

### ISSUE THREAD

**Issue by donZappo** [foundryvtt/pf2e#4223] opened 2022-09-28 02:40 UTC
We are using rolled stats for character creation. Some of our characters have stats that are below 8. We are unable to input that as a custom ability value. When we enter it, it resets the ability to a minimum of 8.

**Comment by stwlam** [comment] 2022-09-28 02:42
Duplicate of #3664, fixed with #4059. You'll just need to update the pf2e system.

**Closed by stwlam** 2022-09-28 02:42 UTC
Labels: duplicate
