### ISSUE TITLE
(Bug) Unable to drag items to other inventories

### ISSUE THREAD

**Issue by Patrick-Moraes** [foundryvtt/pf2e#12244] opened 2023-12-15 00:05 UTC
With the new 5.11.0, there is a bug with dragging items to different inventories, be it the party stash, or other player sheets. The item shows up on the new sheet only while you have it open, but bulk is not opened, and the item is not usable, and goes back to the original sheet upon closing and opening the sheets again.

**Comment by stwlam** [comment] 2023-12-15 00:07
Duplicate of #12231

**Closed by stwlam** 2023-12-15 00:07 UTC
Labels: bug, duplicate
