### ISSUE TITLE
'Munitions Crafter''s Daily Crafting button always makes Medium items instead of the size of the crafter.

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#10256] opened 2023-09-21 17:58 UTC
If you're using a Tiny character and use Munitions Crafter, it seems to default to making Medium items with your Reagents instead of ones the character's size.

**Comment by stwlam** [comment] 2023-09-21 18:10
Duplicate of #6981

**Closed by stwlam** 2023-09-21 18:10 UTC
Labels: duplicate
