### ISSUE TITLE
Feature Request: Only use selected sources

### ISSUE THREAD

**Issue by Tovrin** [foundryvtt/pf2e#6676] opened 2023-02-28 09:01 UTC
I'd like the option to configure a world to use only have access to selected sources to be used within Foundry VTT.

For example, as part of my campaign, I'd like to only use the Core Rules, APG as well as Bestiary 1 and 2.  I don't want to use any of the other rule books or supplements and don't want them to appear in the compendium.  I especially do not want character options (feats and so on) to be available to players.  If I decide to add other sources later, I'd like to select them as I go.

**Comment by simonward** [comment] 2023-02-28 09:06
In progress: https://github.com/foundryvtt/pf2e/pull/6476

**Comment by Tovrin** [comment] 2023-02-28 09:10
Awesome!! :)

**Comment by stwlam** [comment] 2023-03-01 06:53
Duplicate of #3957

**Closed by stwlam** 2023-03-01 06:53 UTC
Labels: feature request
