### ISSUE TITLE
Resistance to Critical Hits and Precision Damage

### ISSUE THREAD

**Issue by Karumac** [foundryvtt/pf2e#9299] opened 2023-08-13 16:21 UTC
Choosing Critical Hits or Precision work properly with Immunity but do not work with Resistance or Weakness.

The first image shows Immunity working properly.
![Immune2Critz](https://github.com/foundryvtt/pf2e/assets/16528457/5587b58a-8bd4-4f16-b2cf-dcd198d62615)
The second image shows that Resistance does not trigger any subtraction at all even though it should.
![Resistance Failure](https://github.com/foundryvtt/pf2e/assets/16528457/5ac3cdcd-77c8-4e0c-b7ba-ff0861c86dfd)
The third image shows that these Damage Types are valid choices in the Drop Down Menu.
![Drop Down](https://github.com/foundryvtt/pf2e/assets/16528457/ed151ef1-89ba-4378-8ccc-891380ed2b79)

This effect does exist on the item Jellyfish Oil ( https://2e.aonprd.com/Equipment.aspx?ID=1959 ) but this is not about implementing the item. This is about subtracting the damage properly when applying it to an actor.

**Comment by stwlam** [comment] 2023-08-13 16:23
Duplicate of #8018

**Closed by stwlam** 2023-08-13 16:23 UTC
Labels: duplicate
