### ISSUE TITLE
Barbarian's Dragon Transformation feat has issues with Dragon Form spell effects

### ISSUE THREAD

**Issue by pxinin** [foundryvtt/pf2e#16438] opened 2024-09-07 23:55 UTC
Dragon Transformation is not adding rage damage to dragon Battle Form.

I am sharing a little fix we made to make it work for now, hope it helps people with the same issue. Rage flat modifier rule works on Dragon Form effects if the system checks a "battle-form" predicate in it. We are playing with this little hack in the Rage action rules, on the flat modifier predicate (check the last "or", it adds a "batte-form" check, even though it always checks to true):

![image](https://github.com/user-attachments/assets/4e3f82b3-839f-478b-85d5-b242a632a603)

**Comment by TikaelSol** [comment] 2024-09-08 17:01
Duplicate of #5632

This fix won't be added in the system since it would hit other battle forms as well. Likely we simply need a new version of the dragon form effect to handle barbarian specifically.

**Closed by TikaelSol** 2024-09-08 17:01 UTC
Labels: duplicate
