### ISSUE TITLE
Feature request: Specific spellslots and spellbook entries for curriculum spells

### ISSUE THREAD

**Issue by denDAY04** [foundryvtt/pf2e#13658] opened 2024-02-10 15:34 UTC
As the title explains, I think it would be a nice feature for the Wizard to have dedicated spellslots and maybe some indication in the spellbook for spells that belong to their curriculum (assuming they are not from the School of Unified Magical Theory). 

I suppose the easy way to deal with this for now is to have a separate prepared spellcasting entry that's only for curriculum spells, but maybe it would be nice to have it as part of their main arcane spells?

**Comment by stwlam** [comment] 2024-02-10 19:58
Duplicate of #4882

**Closed by stwlam** 2024-02-10 19:58 UTC
Labels: duplicate, feature request
