### ISSUE TITLE
Crafting alchemical Ammunition in Batches Size

### ISSUE THREAD

**Issue by Muhammet-Ucar** [foundryvtt/pf2e#6912] opened 2023-03-13 01:05 UTC
We discussed in discord about the amount of alchemical ammunition that you are allowed the carf in Batches. In Foundry it is set to 10, but i think it should be 4.
![Ammo](https://user-images.githubusercontent.com/50582386/224586096-53294b54-d275-449b-9ca3-aabdcd65c127.PNG)

The Rule for that: You can [Craft](https://2e.aonprd.com/Actions.aspx?ID=43) items with the [consumable](https://2e.aonprd.com/Traits.aspx?ID=36) trait in batches, making up to four of the same item at once with a single check. This requires you to include the raw materials for all the items in the batch at the start, and you must complete the batch all at once. You also Craft non-magical ammunition in batches, using the quantity listed in the [Ranged Weapons table](https://2e.aonprd.com/Weapons.aspx) (typically 10).

They are non-magiucal ammunition, but the dont have a quantity listed. Thats why the size should be 4 if you craft them in Batches. I hate that ruling tho, so its fine if you ignore it :)

**Comment by avagdumortesin** [comment] 2023-03-13 02:24
From the Munitions Crafter feat (Guns & Gears, p 111):

> If you use a batch of infused reagents to create basic level-0 ammunition such as black powder cartridges or black powder doses, you produce 10 rounds of ammunition.

Since there is no specific rule beyond that for alchemical ammunition, the generic "typically 10" from the CRB is the default. Absent a clarification or errata from Paizo, this is working as expected.

**Comment by nikolaj-a** [comment] 2023-03-13 02:27
The alchemical ammunition from Treasure Vault are all higher level than zero, though.

**Comment by shemetz** [comment] 2023-03-15 22:20
I think their crafting size should be reduced to 1, when used for feats like Munitions Crafter.  The "batches of 4" part is only for crafting with money, which - I think - is less common than crafting with daily reagents.  Therefore, when dragging alchemical ammunition to the crafting tab's formulas I expected it to set the batch size as 1, just like bombs, rather than 10 (or 4).

**Comment by stwlam** [comment] 2023-03-17 06:55
Duplicate of #1903

**Closed by stwlam** 2023-03-17 06:55 UTC
Labels: duplicate
