### ISSUE TITLE
Animated and Vitalizing Runes not sorted alphabetically in Property Runes

### ISSUE THREAD

**Issue by MothMariner** [foundryvtt/pf2e#16437] opened 2024-09-07 23:13 UTC
Applying Property Runes to weapons, the Animated rune has correctly replaced the Dancing rune, but still appears where Dancing was in the list, out of alphabetical order.
Looking at the screenshot I took, Vitalizing is suffering this problem as well.

![Screenshot 2024-09-08 at 00 11 05](https://github.com/user-attachments/assets/c7b63a1e-12e1-40fe-a080-a32fc87f0e32)

pf2e 6.3.1

**Comment by ammalagonc** [comment] 2024-09-14 00:40
Duplicate of #15472
Thanks for reporting this issue.

**Closed by ammalagonc** 2024-09-14 00:40 UTC
Labels: duplicate
