### ISSUE TITLE
[Request] Filter Crafting Formulas by Type

### ISSUE THREAD

**Issue by LonePaladin** [foundryvtt/pf2e#6085] opened 2023-02-01 23:59 UTC
I have a dedicated crafter in my party, and it's hard for him to sort out what items are alchemical or magical or snares. The formula list in the Crafting tab needs buttons to filter by type.

**Comment by TikaelSol** [comment] 2024-08-06 06:29
Duplicate of #1777

**Closed by TikaelSol** 2024-08-06 06:29 UTC
Labels: feature request
