### ISSUE TITLE
Critical hit immunity no longer working

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#16314] opened 2024-08-29 21:28 UTC
It looks like the critical damage immunity no longer works when applying damage. see example with sewer ooze
![image](https://github.com/user-attachments/assets/9a691349-731e-4849-8e32-dc871fc8c9d7)

**Comment by stwlam** [comment] 2024-08-29 21:34
Duplicate of #16229

**Closed by stwlam** 2024-08-29 21:34 UTC
Labels: duplicate
