### ISSUE TITLE
Wrong description for captivator feat

### ISSUE THREAD

**Issue by evi11y** [foundryvtt/pf2e#7418] opened 2023-04-15 17:03 UTC
![bug report](https://user-images.githubusercontent.com/130858977/232239881-0051338d-9bc0-4692-a36f-57e0ea12188f.png)
The Captivator intensity has the same description as basic spellcasting in the journal entry for archetypes.

**Comment by simonward** [comment] 2023-04-15 17:29
Duplicate of https://github.com/foundryvtt/pf2e/issues/6195

Please update your system.

**Closed by simonward** 2023-04-15 17:29 UTC
