### ISSUE TITLE
Advanced Hunter Trick feat-no dropdown bonus feat

### ISSUE THREAD

**Issue by farabor** [foundryvtt/pf2e#8555] opened 2023-07-03 23:49 UTC
The Advanced Hunter Trick feat is not creating a slot below it to put what ranger feat you take with it,  like the basic one does

**Comment by TikaelSol** [comment] 2023-07-04 19:00
Duplicate of #1956

This is a known limitation of the system currently.

**Closed by TikaelSol** 2023-07-04 19:00 UTC
