### ISSUE TITLE
[Bug] Upgrade to Darkvision RE

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/pf2e#12414] opened 2023-12-20 06:50 UTC
The rules element for upgrading ancestry low-light vision into darkvision does not seem to be working; an actor & associated token are not receiving darkvision on their sheet or in their actual vision detection.

### Steps to Recreate

1. Create a PC. 
2. Give them an ancestry such as elf that receives low-light vision.
3. Give them a heritage such as nephilim or changeling that upgrades their vision to darkvision. The actor will fail to receive darkvision here.

### Expected Behavior

The actor & token have low-light vision upgraded to darkvision.

### Screenshots & Video

https://github.com/foundryvtt/pf2e/assets/99844555/98d71976-672c-4745-b753-52826645f9ae

### Info

Foundry 11.315
PF2E 5.11.5
All modules disabled.

**Comment by stwlam** [comment] 2023-12-20 07:04
Duplicate of #12404

**Closed by stwlam** 2023-12-20 07:04 UTC
Labels: duplicate
