### ISSUE TITLE
Multiple-use consumables display use deductions in inventory stacks

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#11932] opened 2023-12-02 03:42 UTC
**How to Reproduce**

* Take any PC hero, add a repeating hand crossbow.
* Add two full repeating hand crossbow magazines to the PC.  It should be quantity 2 of 5/5, not two separate stacks.
* Fire the hand crossbow
* Observe that the PC now has two magazines of 4/5, effective'y having gone from 10 to 8 bolts.

**Expected Behavior**

* It should either be impossible to stack repeating magazines, or when firing, the magazines should be separated, with the repeating crossbow holding a single 4/5 magazine and the inventory having a separate 5/5 magazine.

**Comment by CarlosFdez** [comment] 2023-12-02 03:43
Its not a bug, but rather a shoddily made feature. If you expend all the 5 bolts, it reduces quantity by one and then gets back to 5 bolts, assuming it works correctly.

**Comment by maplealmond** [comment] 2023-12-02 19:02
This makes a lot more sense, and after testing, works as described.

Unfortunately from a user perspective it ends up being completely unusable and necessitates a mod to accurately track weapons as used in the game world.  Specifically, a PC with 12 repeating bolts doesn't really have "12 repeating bolts" they have two magazines with 5 repeating bolts and one with 2 bolts, and they will almost certainly go into a fight with all 5 loaded.

Having repeating ammo not stack, and having it show the charges, not the quantity in the selector would fit the actual player use.  A "consolidate ammo" option which rebalances identical types (e.g. a player with two air repeater magazines with two pellets each would almost assuredly want to easily convert that into a single air repeater magazine with four pellets) would be useful as well.

**Comment by stwlam** [comment] 2023-12-02 19:34
Closing as user histrionics

**Closed by stwlam** 2023-12-02 19:34 UTC
Labels: wontfix, ui/ux
