### ISSUE TITLE
Resistant armor runes not applying the resistance damage.

### ISSUE THREAD

**Issue by pedrodrf** [foundryvtt/pf2e#14655] opened 2024-05-08 00:20 UTC
As title, the resistant armor rune is not applying the resistance to the character wearing the armor. IWR was turned ON and I have tried on a new world with no modules activated. 
Foundry version is 11 build 315 and pf2e version is 5.15.3
![image](https://github.com/foundryvtt/pf2e/assets/109934746/3055c47f-fadf-4c5b-9ec6-6172693f1c6a)

**Comment by stwlam** [comment] 2024-05-08 00:29
Duplicate of #10966

**Closed by stwlam** 2024-05-08 00:29 UTC
Labels: duplicate
