### ISSUE TITLE
Players can see damage rolls with meta game rules on.

### ISSUE THREAD

**Issue by Dargboota** [foundryvtt/pf2e#5537] opened 2023-01-07 00:23 UTC
When the gm private rolls for damage, be it a spell or strike, the combination of the damages tell them exactly what the roll is, even damage types.

--From a strike
(Player View)
![image](https://user-images.githubusercontent.com/116990169/211121100-71a37d5b-3869-4f17-915e-c7f0ff4e3dfd.png)
(Gm View)
<img width="212" alt="image" src="https://user-images.githubusercontent.com/116990169/211121255-aa96f854-8ee1-4f50-9316-490036d5776b.png">

--From Phantom Pain
(Player View)
![image](https://user-images.githubusercontent.com/116990169/211121137-78eecf7f-0bea-4add-8e8a-cd0dd64f3ac6.png)
(Gm View)
<img width="208" alt="image" src="https://user-images.githubusercontent.com/116990169/211121286-d33e83ce-9841-44a7-9af0-41698e0f8fea.png">

Non-combined damage is still hidden like normal.
<img width="139" alt="image" src="https://user-images.githubusercontent.com/116990169/211121411-f64f3aaf-6eb7-4abb-8725-b25aa942dc3d.png">

**Comment by stwlam** [comment] 2023-01-07 00:32
Duplicate of #5520

**Closed by stwlam** 2023-01-07 00:32 UTC
Labels: duplicate
