### ISSUE TITLE
Opening and closing an item sheet while it being affected by a `AdjustStrike` RE will make the changes permanent (and more)

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#13909] opened 2024-02-23 00:15 UTC
For instance, having a `AdjustStrike` RE with a `property-runes` property will permanently add the rune to the item.

Another notable point is that adding such RE will not modify the weapon/strike name, so there is no telling that the rune effect is actually active when rolling the attack or damage anywhere.

Lastly, it doesn't seem to be working with handwraps.

**Comment by stwlam** [comment] 2024-09-23 00:45
Duplicate of #11366

**Closed by stwlam** 2024-09-23 00:45 UTC
Labels: bug, duplicate

**Comment by reonZ** [comment] 2024-09-23 10:59
I am the original, not the clone !!
