### ISSUE TITLE
Some Ancestries have the wrong Senses

### ISSUE THREAD

**Issue by Bhalandros** [foundryvtt/pf2e#12853] opened 2024-01-08 07:51 UTC
Some Ancestries should have Low-Light Vision or Darkvision, but don't.
![vision](https://github.com/foundryvtt/pf2e/assets/27706374/99366892-3bbf-4d04-9559-6feb4832a78e)
When applying the race, it gives the character Low-Light vision, but only until the Ancestry is opened and then closed, at which point it disappears.
![rac e](https://github.com/foundryvtt/pf2e/assets/27706374/e1bf6728-95f1-4381-8ea1-f30c717154e6)
![ttst](https://github.com/foundryvtt/pf2e/assets/27706374/9bc866dd-8d68-461c-8bf2-ae51850ebed0)
![Capture](https://github.com/foundryvtt/pf2e/assets/27706374/2de55f68-8fb9-418c-9e05-bddf2b1a2f1f)
It also seems to disappear when adding a Heritage that modifies vision, such as Nephilim, which gives Darkvision if the character already has Low-Light Vision.
![wawa](https://github.com/foundryvtt/pf2e/assets/27706374/2e363cbd-c1ca-400d-acac-c1d8a9d1978e)
Here I modify the Ancestry to have Low-Light Vision, which makes it do this.
![vnm,vnxv](https://github.com/foundryvtt/pf2e/assets/27706374/c3608af4-4e8d-40ce-a4a3-f43e2a9797ce)

**Comment by stwlam** [comment] 2024-01-08 07:58
Duplicate of #12835

**Closed by stwlam** 2024-01-08 07:58 UTC
Labels: duplicate
