### ISSUE TITLE
Feature Request: Add Health Stat Boxes/Input Fields for Weapons

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#12622] opened 2023-12-30 21:34 UTC
When you go to edit them Armour has boxes to mark down their hardness, hp, and damage taken, but weapons don't - which is a pain when dealing with Oozes. Can we get those added?

**Comment by stwlam** [comment] 2023-12-30 21:44
Duplicate of #743

**Closed by stwlam** 2023-12-30 21:44 UTC
Labels: duplicate
