### ISSUE TITLE
Titan's Breaker not bypassing Construct Spirit immunity

### ISSUE THREAD

**Issue by SaintKatherine** [foundryvtt/pf2e#17816] opened 2024-12-24 00:52 UTC
![image](https://github.com/user-attachments/assets/807daf17-1081-49da-afae-050641b8fe91)

![image](https://github.com/user-attachments/assets/d82d2315-b8fa-4ae8-ac01-75a9347a6fd3)

Titan's Breaker should be bypassing the Constructs Spirit immunity. Divine Spark is selected as in Titan's Breaker, and can be seen in the damage breakdown yet when taking the damage as the construct it is immune to it,

**Comment by pedrogrullada** [comment] 2024-12-24 00:56
Duplicate of #13537

**Closed by pedrogrullada** 2024-12-24 00:56 UTC
