### ISSUE TITLE
Wand Activations don't cast the spell

### ISSUE THREAD

**Issue by Brandon-Wolff** [foundryvtt/pf2e#13670] opened 2024-02-10 22:17 UTC
When clicking the "Cast" button for a wand in the character sheet's activations tab, the wand is marked as used but nothing else happens; the spell isn't pasted in the chat, no dice are rolled.

**Comment by stwlam** [comment] 2024-02-10 22:23
Duplicate of #13455: try disabling modules

**Closed by stwlam** 2024-02-10 22:23 UTC
Labels: duplicate
