### ISSUE TITLE
[Remaster] Incorrect total number of familiar abilities on Witch familiar

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#11504] opened 2023-11-17 17:09 UTC
Player Core pg. 181
> Your familiar gains two additional familiar abilities: one of these is a unique ability based on your patron and is always selected, and the other is an additional familiar ability that can be selected daily as normal.

Witches in the remaster gain two additional familiar abilities instead of just one, albeit one them happens to be a fixed ability from their patron. The familiar sheet understandably still treats it as only one additional ability, and so it lists 3 as "# number of familiar abilities" instead of 4.

**Comment by avagdumortesin** [comment] 2023-11-18 09:01
This appears to be a duplicate of https://github.com/foundryvtt/pf2e/issues/11449.

**Closed by avagdumortesin** 2023-11-18 09:01 UTC
Labels: data error, remaster

**Comment by pedrogrullada** [comment] 2023-11-18 17:42
This issue is about the number of abilities shown in the familiar sheet,
not about what's missing from the compendium. If both of those can be
tracked via the cited issue, fair enough, but that wasn't what I had in
mind.
