### ISSUE TITLE
Reverse Engineering feat not accepted as an Archetype feat

### ISSUE THREAD

**Issue by LordGoggles** [foundryvtt/pf2e#3352] opened 2022-08-04 00:18 UTC
The feat can be applied as a bonus feat, but when adding as an Archetype feat, the following error is displayed:
![image](https://user-images.githubusercontent.com/110574933/182735910-7f4e8c73-a733-488c-8e1c-ddb747fa3bf9.png)

When switching the feat to a different type, it is applied to the sheet as normal. It only happens when adding as an Archetype feat.
This is when it is being added as a 4th level feat using the Free Archetype variant rules.

I have tried the following to solve this issue:
- Reinstalled Foundry
- Reinstalled PF2 system files
- Making a fresh world, fresh actor, and attempting to apply the feat

I also noticed that, when adding the Reverse Engineering feat as a different kind of feat, a duplicate line of code is generated for an actor in the actors.db file in the world folder. It's usually a copy of the actor I'm trying to assign the feat to, but sometimes the data doesn't appear to be a perfect copy, or it copies another actor, seemingly at random.

**Comment by leerhund** [comment] 2022-08-04 00:30
It's a Skill feat. Free Archetype feats are Class feats RAW.

https://github.com/foundryvtt/pf2e/wiki/The-CounterFAQ#free-archetype-and-archetype-skill-feats

**Comment by SpartanCPA** [comment] 2022-08-04 01:32
Closing as the system is working as intended. If you would like to put the feat into the slot anyway, we recommend altering the feat type in your game

**Closed by SpartanCPA** 2022-08-04 01:32 UTC

**Comment by LordGoggles** [comment] 2022-08-04 01:36
That works! Thank you!
