### ISSUE TITLE
Could we add tags, or anything really, to runes to be able to filter them?

### ISSUE THREAD

**Issue by manituan** [foundryvtt/pf2e#11322] opened 2023-11-14 12:31 UTC
I'm not able to filter, in code, the compendium runes by tag, subgroup or anything really. They're magical, but as many other things.
If it's not too much trouble could we add new rune (property/potency) tags to these magic items? 

Thanks a lot.

**Comment by stwlam** [comment] 2023-11-15 03:35
Duplicate of #6407

**Closed by stwlam** 2023-11-15 03:35 UTC
Labels: duplicate, feature request
