### ISSUE TITLE
Advanced Alchemy - Rule elements

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#17415] opened 2024-11-21 16:13 UTC
According to the description, the number of alchemical items that can be produced is 4 + your Intelligence modifier.
Meanwhile, in the rules it is:
`{"key":"ActiveEffectLike","mode":"upgrade","path":"system.resources.crafting.infusedReagents.max","predicate":["class:alchemist"],"value":"@actor.level + @actor.abilities.int.mod"}`

It should be:
`{"key":"ActiveEffectLike","mode":"upgrade","path":"system.resources.crafting.infusedReagents.max","predicate":["class:alchemist"],"value":"4 + @actor.abilities.int.mod"}`

**Comment by CarlosFdez** [comment] 2024-11-22 04:09
Duplicate of https://github.com/foundryvtt/pf2e/issues/15647

**Closed by CarlosFdez** 2024-11-22 04:09 UTC
