### ISSUE TITLE
Feature Request: add a way to track spells learnt for spontaneous casters.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#14011] opened 2024-02-29 01:17 UTC
so i have an issue where id like a way for my players to track the spells learnt as a spontaneous caster. similar to the spell book for prepared casters but not needing to put it into the spell book. this is useful for retraining.

**Comment by stwlam** [comment] 2024-02-29 06:02
Duplicate of #502

**Closed by stwlam** 2024-02-29 06:02 UTC
Labels: duplicate
