### ISSUE TITLE
{Bug} Appears to be bug in compendium browser sources

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#15727] opened 2024-08-03 00:20 UTC
Intermittent bug that fails to display the whole list of sources, the parsed list changes slightly each time. Some sources are missing on one load but next time you load the sources they will show but then others will be missing.

**Comment by stwlam** [comment] 2024-08-03 09:22
Duplicate of #15606

**Closed by stwlam** 2024-08-03 09:22 UTC
Labels: duplicate
