### ISSUE TITLE
Daily Crafting with the Munitions Crafter feat doesn't currently allow you to make as much ammunition as the feat says you should.

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#10257] opened 2023-09-21 18:03 UTC
Munitions Crafter says if you have the feat then "[i]f you use a batch of infused reagents to create basic level-0 ammunition such as black powder cartridges or black powder doses, you produce 10 rounds of ammunition." but the Crafting Tab's Daily Crafting button seems to not know about this and says it costs 5 reagents to make 10 rounds of all the level-0 ammunition of the 'Rounds' variety I tried.

**Comment by stwlam** [comment] 2023-09-21 18:09
Duplicate of #1903

**Closed by stwlam** 2023-09-21 18:09 UTC
Labels: duplicate
